### ISSUE TITLE
Enable HTTPS for Content Routing Type = HTTP

### ISSUE THREAD

**Issue by joepeters27** [Comcast/traffic_control#1023]
Would like to enable HTTPS for delivery services using HTTP 302 redirects, as is currently possible when using DNS as the Content Routing type.

**Comment by smalenfant** [comment]
Is this about using HTTP to Request Router and then return an HTTPS location or an end-to-end HTTPS? What I would require is simply a `Location: https://bla`while using HTTP to TR.

**Comment by knutsel** [comment]
this is about TR listening on 443 w HTTPS. 

you want HTTP routing and HTTPS caching?

**Comment by smalenfant** [comment]
@knutsel Yes. Should I open a separate issue?

**Comment by elsloo** [comment]
@smalenfant yes, please create a new issue labeled with enhancement and Traffic Router.
