### ISSUE TITLE
RELEASE1.4.0-RC4 - Traffic Ops installs two migrations with the same name 

### ISSUE THREAD

**Issue by dneuman64** [Comcast/traffic_control#1059]
The RC4 installer creates two migrations with the same name in /opt/traffic_ops/app/db/migrations. 

```
20151207000000_add_job_status.sql
20151207000000_unique_email.sql
```

This seems to be related to not creating the installer from a "clean" directory because the renamed migration is also there:  

```
-rw-r--r-- 1 trafops trafops 1382 Feb 12 21:49 20151207000000_add_job_status.sql
-rw-r--r-- 1 trafops trafops  286 Feb 12 21:49 20151207000000_unique_email.sql
-rw-r--r-- 1 trafops trafops 1382 Feb 12 21:49 2015120800000_add_job_status.sql
```

**Comment by dangogh** [comment]
leftover remnant in rpmbuild dir on our jenkins server.  Changed configuration to delete that dir prior to each build.   Confirmed that file is no longer in the resulting rpm.

**Comment by dangogh** [comment]
change to Jenkins config eliminates this issue..
