### ISSUE TITLE
creating https delivery service and not setting to active still looks for cert.

### ISSUE THREAD

**Issue by G4m30v3r** [Comcast/traffic_control#1086]
Que'ed and snapshotted - delivery service was not set to active. On syncds it err's looking for DS cert.
ERROR Received error code 400 for https://trafficops/api/1.1/deliveryservices/hostname/deliveryservicename/sslkeys.json from Traffic Ops!
FATAL SSL URL: https://trafficops/api/1.1/deliveryservices/hostname/deliveryservicename/sslkeys.json returned 400. Exiting.

Just generating a ssl key and error goes away.
Copying /tmp/ort/123/trafficserver/config_trops deliveryservicename .cer to /opt/trafficserver/etc/trafficserver/ssl//deliveryservicename_cert.cer
ERROR Copying /tmp/ort/123/trafficserver/config_trops/deliveryservicename.key to /opt/trafficserver/etc/trafficserver/ssl//deliveryservicename.key

**Comment by mtorluemke** [comment]
I believe this is in the generation of ssl_multicert.config
