### ISSUE TITLE
[ERROR] No TrafficMonitor servers found for: <cdn>

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#109]
Wheme there is no Traffic Monitor configured, the script keep failing. Logging an error is useful, but could it be a WARNING note instead without the trace?

Suggesting only. low priority.

**Comment by elsloo** [comment]
Looks like this is something in Traffic Ops:

TrafficMonitorConnection.pm:                                    confess("No TrafficMonitor servers found for: $cdn");

**Comment by jheitz200** [comment]
Duplicate ticket #403
