### ISSUE TITLE
Adding more stats to astats

### ISSUE THREAD

**Issue by faisalusuf** [Comcast/traffic_control#1104]
While comparing output of astats with stats_over_http, the "proxy.node" level statistics found missing. Below are the example stats that can be helpful to graph cache performance. Kindly add these stats in the astats.

**proxy.node.bandwidth_hit_ratio: "0.153904",
proxy.node.hostdb.hit_ratio: "0.823022",
proxy.node.cache.percent_free: "0.989006",
proxy.node.cache_hit_ratio: "0.311883",
proxy.node.cache_hit_mem_ratio: "0.132488",
proxy.node.cache_total_hits: "191683",
proxy.node.cache_total_hits_mem: "81427",
proxy.node.cache_total_misses: "422916",**

Thanks
F.

**Comment by PSUdaemon** [comment]
I think this issue is resolved. Was a misplaced config file.
