### ISSUE TITLE
TO API 2.0 - Retrieve current logged in user

### ISSUE THREAD

**Issue by mitchell852** [Comcast/traffic_control#1115]
Need a way to retrieve "current logged in user". This can be achieved a couple of ways:

1. Create an api endpoint like GET /api/2.0/tm_user/current or

2. The response of /api/2.0/login could look like this { Token: 'blahblah', userId: 50 } and then a call to /api/2.0/tm_user/50 would pull "current user"

**Comment by knutsel** [comment]
The userid is encoded in the JWT Token. You should be able to get it from that?

**Comment by knutsel** [comment]
Actually not 100% sure if that is available on the client, let me do some digging.

**Comment by mitchell852** [comment]
@knutsel - sounds good. thx

**Comment by knutsel** [comment]
Looks like you can. https://thinkster.io/angularjs-jwt-auth sez so. Currently there's 2 claims in the token: 

`
		token.Claims["userid"] = u.Id
		token.Claims["role"] = u.Links.RoleLink.ID
		token.Claims["exp"] = time.Now().Add(time.Hour * 72).Unix()
`

(which also answers your expire question from yesterday, it's 72 hours, not 24.

**Comment by knutsel** [comment]
insert semicolons ;-)

**Comment by mitchell852** [comment]
yep, jwt is where it's at. no need for an apiendpoint to pull current user.
