### ISSUE TITLE
LDAP search filter contains Active Directory specific attributes

### ISSUE THREAD

**Issue by elsloo** [Comcast/traffic_control#1129]
The search filter used to locate user DNs contains hard coded values that only work with Active Directory:

`$mesg = $ldap->search( base => $search_base, filter => "(&(objectCategory=person)(objectClass=user)(sAMAccountName=$username))" );`

This search filter should be configurable and should be in ldap.conf. Instead, it's hard coded in TrafficOps.pm.

For example, this search filter would work with most non-AD based LDAP severs:

`(&(objectClass=inetOrgPerson)(uid=$username))`

**Comment by mitchell852** [comment]
moved to jira
