### ISSUE TITLE
Traffic Ops Delivery Service change for Max DNS requests returns to 0

### ISSUE THREAD

**Issue by G4m30v3r** [Comcast/traffic_control#1156]
Editing Max DNS requests changes it to default 0 on save.

**Comment by elsloo** [comment]
@G4m30v3r I just tested this in master (what will become 1.5.0) and I cannot reproduce the issue.

**Comment by G4m30v3r** [comment]
produced this consistently on 1.4.0.2426. Showed output to elsloo directly.

**Comment by elsloo** [comment]
Confirmed that this affects 1.4.x and a fix needs to be applied; most likely a backport from a commit that has already been made to master.

**Comment by dneuman64** [comment]
closed by #1182
