### ISSUE TITLE
Change Log count in UI is not being reset

### ISSUE THREAD

**Issue by elsloo** [Comcast/traffic_control#1171]
The number of changes that appears in the change log is not being reset when the change log is viewed in the web UI. Typically once you visit the change log page the count resets (goes away), then only reappears after an entry is written to the change log.

**Comment by elsloo** [comment]
![screen shot 2016-03-16 at 3 55 32 pm](https://cloud.githubusercontent.com/assets/4641376/13830144/7178fc42-eb90-11e5-8bc6-7e83461f1a3d.png)

**Comment by knutsel** [comment]
close, Angular UI will fix.
