### ISSUE TITLE
Multi Site origin requires different hostnames

### ISSUE THREAD

**Issue by chiefcll** [Comcast/traffic_control#1176]
http://traffic-control-cdn.net/docs/latest/admin/quick_howto/multi_site.html

Traffic ops is requiring the hostnames to be unique. However, it should be a combination of hostname + domain name which needs to be unique.

Test Case:

my-app.g1.kabletown.net
my-app.g2.kabletown.net

That should be acceptable.

**Comment by dg4prez** [comment]
Fixed.
