### ISSUE TITLE
TO: Add per-delivery service geo provider

### ISSUE THREAD

**Issue by mtorluemke** [Comcast/traffic_control#1202]
Currently, the default is assumed to be MaxMind. Moving forward, we want to at least make Neustar available as a configuration option on a delivery service. 

Should we pop up a notification to inform the user of where to go to get a Neustar license? Not sure...I think we're okay without it.

**Comment by elsloo** [comment]
- The add/edit delivery service UI should have a dropdown for selecting the geolocation provider
- The label for the new dropdown should be "Geolocation Provider"
- The default geolocation provider should say something like "Default (MaxMind)"
- The only other option we have right now is Neustar which should be an option
- Each provider should have a "friendly" name such as "Neustar" that we use in the dropdown, with a corresponding value that's used in CRConfig
- The value that appears in CRConfig when Neustar is selected should be `neustarGeolocationService`
- If the user opted to use the default, no key/value pair for geolocationProvider should appear in the CRConfig
- The CRConfig snapshot reflects any changes to the geolocation provider when a delivery service is created/modified (absence of `geolocationProvider` when set to MaxMind, presence when set to Neustar)
- The API endpoints that serve delivery service data should be updated to include the geolocation provider in the JSON (this *can* include the default of MaxMind)
- The "unfriendly" name for MaxMind is `maxmindGeolocationService` - this could be what is used in the JSON served by the API

The code in Traffic Router is expecting the geo provider to be specified within the CRConfig as follows:

```
...
deliveryServices: {
    some-deliveryservice: {
        ...
        geolocationProvider: "neustarGeolocationProvider",
        ....
    }
...
```

@trevorackerman please keep me honest here and post any additional requirements as necessary.

**Comment by trevorackerman** [comment]
I just updated the above crconfig example. After yesterday's conversation you helped me remember that we wanted to be able to control the location where TR will download data files for specific geolocation services.

**Comment by dneuman64** [comment]
@trevorackerman:  I don't think we want to have a different dataUrl per Delivery Service, do we?  That is what the current example shows.

**Comment by elsloo** [comment]
I agree with @dneuman64; we don't need to add that to the delivery service config as the instance of neustarGeolocationService is shared. We can get the polling URL from the "config" section of the CRConfig easily by simply adding a profile parameter in Traffic Ops, no code required.

**Comment by trevorackerman** [comment]
Yeah, I agree with you guys. I don't understand the profile thing. So you'll have to show me.

**Comment by dangogh** [comment]
ok..   working on it now..    You guys can take it and tweak as necessary once it's merged in.
