### ISSUE TITLE
For mulit-site Origin, the same origin servers failed to be associated with multiple CDNs

### ISSUE THREAD

**Issue by jianli123** [Comcast/traffic_control#1208]
With MSO,  it's a normal case that the same origin servers would be shared among CNDs.   But TrafficOps database doesn't allow the  Origin Servers (with same IP & hostname) be used as MSO for different CNDs.

**Comment by smalenfant** [comment]
I had the same problem. I created another Traffic Ops instance to take of the issue.

**Comment by jianli123** [comment]
@smalenfant what is your issue ID? thanks

**Comment by smalenfant** [comment]
I didn't put an issue.
