### ISSUE TITLE
Adding cache to server table doesn't add corresponding entry to servercheck table

### ISSUE THREAD

**Issue by mtorluemke** [Comcast/traffic_control#121]
Loading 'Server Checks' UI results in a datatables error.

**Comment by smalenfant** [comment]
Tested in 1.1.3. Problem still present. While we were provisioning more Mid Caches, the Health->Server Checks failed to display. After a Ping check was working, it finally rendered. I guess just add a dummy Mid-Cache to reproduce.

**Comment by knutsel** [comment]
Huh! I'll take a look.

**Comment by mtorluemke** [comment]
@dangogh put in a(nother) fix in 1.1.5. @smalenfant please retest when 1.1.5 is released.

**Comment by mtorluemke** [comment]
Reopen if still an issue after 1.1.5 is released.
