### ISSUE TITLE
ip_allow.config generation coalesce to IPv6 /48 subnets

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#1216]
The `ip_allow.config` generation is doing coalescing on a /48 subnet basis. This seems rather large.

I would propose to coalesce to /64 instead. This might depends on each provider usage of IPv6 subnet. I do use /127 for my caches which might not be suitable for those who uses /64.

Any comments?

**Comment by mtorluemke** [comment]
Seems we should make it configurable...

**Comment by knutsel** [comment]
agree.

**Comment by dg4prez** [comment]
Completed in 2.0.
