### ISSUE TITLE
Update Traffic Stats to allow for custom URL stat collection

### ISSUE THREAD

**Issue by dneuman64** [Comcast/traffic_control#1236]
As a cdn engineer I need to be able to provide a custom URL to Traffic Stats and have traffic stats use it to collect custom stats from traffic monitor.

AC:
A custom URL can be defined to gather stats
Traffic Stats will consume the URL and use it to gather stats
Traffic Stats will store the stats in InfluxDb in a way that they can be graphed in grafana
Traffic Stats should be able to handle 1 to many of these custom URLs

**Comment by guzzijason** [comment]
Request cancelled per Neuman.
