### ISSUE TITLE
Update create_ts_databases for influxdb 0.10 and greater

### ISSUE THREAD

**Issue by dneuman64** [Comcast/traffic_control#1243]
As of the 0.10.0 version of InfluxDb, the CQ language has changed a bit.  Create_ts_databases needs to be updated to support these new changes.  The current ones will work, but not as well as they could.  For more information see here:  https://docs.influxdata.com/influxdb/v0.10/administration/upgrading/

**Comment by smalenfant** [comment]
Dave, might be a good idea to use the ping API call to get version and set the proper CQ. Although I might think having a non-compiled language tool would be easier to support and modify. Thought?

**Comment by dneuman64** [comment]
Yeah, might be a good idea to figure out version and create CQs accrodingly, but I was kinda just hoping to push everyone to use a version > 0.10 (and actually @PSUdaemon added PING to the client starting in 0.10 I believe).  I will look into that.  As for using a non-compiled language, I just added the the tools to the RPM build for 1.5.0 and I like being able to provide a binary instead of requiring a dependency to run them...

**Comment by dneuman64** [comment]
This was closed as part of #1374
