### ISSUE TITLE
While attempting to regenerate SSL keys in Traffic Ops

### ISSUE THREAD

**Issue by G4m30v3r** [Comcast/traffic_control#1268]
Traffic Ops fatal error occurred while processing your request.
Error at line ()
Can't call method "is_success" on an undefined value at /opt/traffic_ops/app/lib/UI/SslKeys.pm line 127. 

Also, I moticed that deleting and rebuilding the Delivery Service will still pull the old keys, despite the DS being "deleted and rebuilt"

**Comment by smalenfant** [comment]
Confirming issue on 1.5.0RC0.

**Comment by dneuman64** [comment]
This issue only happens on http/https deliveryservices.  The issue is this code:  
```perl
my @example_urls    = UI::DeliveryService::get_example_urls( $self, $ds_id, $ds_regexes, $data, $domain_name, $data->protocol );	
my $hostname = $example_urls[0];
$hostname =~ /(https?:\/\/)(.*)/;
```
if the DS is https only then the first example_url is the https one, if the DS is http/https then its actually the second example_url (`my $hostname = $example_urls[1];`) that we want to use.
