### ISSUE TITLE
Update docs regarding Traffic Server

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#127]
The following shows up in the documentation for Traffic Server :

For “every day changes” such as adding deliveryservices or changing records.config parameters caches should run the script in “syncds” mode out of cron. Example crontab entry:

*/15 \* \* \* \* /opt/ort/traffic_ops_ort.pl syncds warn https://traffops.kabletown.net admin:password > /tmp/ort/syncds.log 2>&1

Although a reference should be made that these scripts are installed automatically by `traffic_ops_ort` and the value should be changed to reflect your CDN.

The database contains: 
- name=cron_ort_syncds
- config=traffic_ops_ort_syncds.cron
- value="*/15 \* \* \* \* root /opt/ort/traffic_ops_ort.pl syncds warn https://tm.kabletown.net admin:password> /tmp/ort/syncds.log 2>&1"

**Comment by knutsel** [comment]
Hey Steve... Patches welcome! Haven't seen your signed CLA yet... This seems like a perfect issue that you could fix yourself.

**Comment by rob05c** [comment]
Fixed in https://github.com/apache/incubator-trafficcontrol/pull/576
