### ISSUE TITLE
Verify Traffic Ops 2.0 endpoints with new schema are correct

### ISSUE THREAD

**Issue by rob05c** [Comcast/traffic_control#1273]
The TO 2.0 code has been fixed to compile with the latest `schema.sql`, but all the endpoints haven't been tested yet. Some are almost certainly broken.

To do this, we need 2.0 data, either from test data or a conversion script to convert old Traffic Ops 1.x databases.

**Comment by robert-butts** [comment]
This is probably no longer relevant, since the new plan is to use PostgREST

**Comment by rob05c** [comment]
This is referring to the old prototype, not the current "Traffic Ops 2.0". No longer applies, prototype is so old now, it will have to be completely reevaluated if it's used.
