### ISSUE TITLE
Verify Traffic Ops 2.0 endpoints HAL is correct with the latest schema

### ISSUE THREAD

**Issue by rob05c** [Comcast/traffic_control#1274]
With the code fixes for the latest schema changes, HAL is almost certainly broken, especially with composite keys. Each endpoint needs verified and fixed if broken. This most likely means fixing the API generator code.

To do this, we need data with the latest schema, either test data or a conversion script to convert old 1.x data.

**Comment by robert-butts** [comment]
This is probably no longer relevant, since the new plan is to use PostgREST.

**Comment by rob05c** [comment]
No longer applies.
