### ISSUE TITLE
ADMIN_DOWN should also not cause parent_pending=1

### ISSUE THREAD

**Issue by mtorluemke** [Comcast/traffic_control#1288]
Currently, only OFFLINE is the status that removes that parent cache from being considered in the child cache's parent_pending key in that child cache's /update/<hostname>. This is important as ORT checks the parent_pending key before processing updates for that cache.

This is the code that likely needs to change in lib/UI/Server.pm:

				while ( my $prow = $rs_parents->next ) {
					if (   $prow->upd_pending == 1
						&& $prow->status->name ne "OFFLINE" )
					{
						$parent_pending{ $rs_servers->single->host_name } = 1;
					}
				}

**Comment by knutsel** [comment]
not sure if i agree... ADMIN_DOWN hosts run ort? This only works if the transition from ADMIN_DOWN to REPORTED or ONLINE forces an ort badass?

**Comment by mtorluemke** [comment]
Hmm, yes, they should. Let me think about that -- perhaps we should more aggressively put caches into an OFFLINE status (with some automation?)? A quick reboot can cause an ORT run to be missed, and propagation delays because of it.

**Comment by mtorluemke** [comment]
Closing issue -- @knutsel is right -- the operations procedure should be such that if a cache cannot successfully complete a 'syncds' ORT run, it should be in OFFLINE.
