### ISSUE TITLE
Traffic Ops postinstall should detect that an installation (configuration) already exists

### ISSUE THREAD

**Issue by mtorluemke** [Comcast/traffic_control#129]

**Comment by mtorluemke** [comment]
@daniel_kirkwood

**Comment by mtorluemke** [comment]
...and not ask to setup a new CDN. Should even work for dev environments? Maybe i'm barking up the wrong tree with this.

**Comment by dangogh** [comment]
lots of work done on postinstall in the past few releases.  I just tried this with 1.5.0-RC3 -- it still runs carton for Perl deps and checks web deps, but runs quickly if no change.  I'm declaring this done...
