### ISSUE TITLE
TC: Ansible Client - Elasticsearch Servers

### ISSUE THREAD

**Issue by jheitz200** [Comcast/traffic_control#1295]
Add api endpoint to gather all ES servers

Acceptance Criteria
- Logs to TO
- Get a list of all ES servers hostnames

**Comment by mitchell852** [comment]
maybe you can use an existing api endpoint with a query param. i.e.

/api/version/servers.json?type=ELASTIC_SEARCH

^^ or maybe id is better. don't know. ?type=76 for example...

**Comment by jheitz200** [comment]
Traffic Ops has an existing api endpoint `api/version/servers?type=ELASTICSEARCH` it just needs to be integrated into the ansible_client api and formatted for use in the ES config file.
