### ISSUE TITLE
TO: add api endpoint for DS's opting into logs

### ISSUE THREAD

**Issue by jheitz200** [Comcast/traffic_control#1298]
Add an api endpoint to get a list of delivery services that have opted into Logs

Acceptance Criteria
- New api endpoint
- Unit tests
- Update docs

**Comment by mitchell852** [comment]
maybe you an piggy back on an existing api endpoint using a query param. i.e.

/api/version/deliveryservices?logsEnabled=true (or whatever your flag is called).

**Comment by dewrich** [comment]
This was done in 1.6
