### ISSUE TITLE
Mid-Cache in state "REPORTED" don't get added to parent.config on Edges

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#132]
As the subject says. If the Mid-Caches are configured as "ONLINE" then all is good. 

Note: I couldn't get the Mid-Caches to show up in Traffic Monitor unless I put them in "REPORTED" state.

**Comment by knutsel** [comment]
We didn't plan on having Traffic Monitor the mid tier caches initially, but plans change... This should be part of a larger feature request to have TM monitor mids.

**Comment by knutsel** [comment]
https://github.com/Comcast/traffic_control/commit/cf52c0879bdfcf3c24ed01362d7d11ae2531c4d6 fixes
