### ISSUE TITLE
Deleting a delivery service does not delete SSL keys from Traffic Vault

### ISSUE THREAD

**Issue by dneuman64** [Comcast/traffic_control#1325]
When a HTTPS delivery service is deleted, the ssl keys from Traffic Vault should also be deleted.

**Comment by smalenfant** [comment]
What if someone wants to re-create the service? They would need to first make sure to save all certificate information outside the database? Let's think about possible scenarios. Might need some certificate management separate from the delivery service. What if a delivery service has also a CNAME and needs 2 different certificates?

I don't have much experience with SSL and Traffic Ops yet. Just started looking into it yesterday.

**Comment by dneuman64** [comment]
There is an option to paste keys, so if you need to you can copy the keys out and then paste them back in.  If a DS needs two different certs than that would be a different scenario and should probably be a different GH issue.

**Comment by limited** [comment]
https://issues.apache.org/jira/browse/TC-305
