### ISSUE TITLE
When Mid-Caches are set to "REPORTED", Traffic Monitor can't poll astats

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#133]
The ip_allow should add the Traffic Monitors to the list of subnets allowed. Maybe Traffic Ops should be added too (server checks).

Current workaround is to add the Traffic Monitor IPs/subnets in the purge_allow_ip list. I didn't see a purge_allow_ip6 parameter (didn't check the code. This might require another enhancement in case the purge IP is v6.

**Comment by knutsel** [comment]
had the wrong issue # in commit message

**Comment by knutsel** [comment]
Confused now - looks like that commit actually fixes the issue, so closing it. Steve - please retest in > 112?

**Comment by smalenfant** [comment]
Will test without the purge_allow workaround against 1.1.2 (make sure there is false positive).

**Comment by smalenfant** [comment]
I was checking the ToCHRCheck.pl script but came across the same issue. ip_allow settings has all the subnets required. 

astats.config has the subnet included
ip_allow.config is missing it

Ends up into a deny since both are required. Seems like astats.config allow_ip/allow_ip6 needs to make it into the Mid Cache ip_allow.config

Please re-open.
