### ISSUE TITLE
RPM git short hash has one too many characters

### ISSUE THREAD

**Issue by elsloo** [Comcast/traffic_control#1330]
When building all Traffic Control RPMs, the Traffic Router and Monitor RPMs contain an additional character in the git short hash. Ensure that the resulting hash matches across all RPMs.

e.g.: `traffic_monitor-1.5.0-3027.8d600a8e6.el6.x86_64.rpm` should be `traffic_monitor-1.5.0-3027.8d600a8e.el6.x86_64.rpm`

**Comment by mtorluemke** [comment]
Looks like Traffic Ops has the same issue.

**Comment by elsloo** [comment]
Doesn't appear to be that way on my side:

```[root@ipcdn-ci-oswcdc-01 RELEASE-1.5.0-RC1]# for file in *; do name=$(echo $file |awk -F\- '{print $1}'); hash=$(echo $file |awk -F. '{print $4}'); hashCount=$(echo -n $hash |wc -c); echo "$name -> $hash = $hashCount"; done |sort -k3
traffic_monitor -> 8d600a8e6 = 9
traffic_router -> 8d600a8e6 = 9
traffic_ops -> 8d600a8e = 8
traffic_ops -> 8d600a8e = 8
traffic_ops_ort -> 8d600a8e = 8
traffic_ops_ort -> 8d600a8e = 8
traffic_stats -> 8d600a8e = 8
traffic_stats -> 8d600a8e = 8
```
