### ISSUE TITLE
1.5.0: Traffic monitor looks for HOSTNAME in /etc/sysconfig/network

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#1339]
When I upgraded to Traffic Monitor 1.5.0, the installation didn't finish and complained about `stderr: FATAL: Unable to find HOSTNAME in /etc/sysconfig/network at /opt/traffic_monitor/bin/traffic_monitor_config.pl line 65.`

Was changed part of this commit https://github.com/Comcast/traffic_control/commit/34914947ffcef12a7f9663b95623af9e941ef24b

All my system answers properly to `hostname` with a full FQDN. `hostname -f` could also be used.

**Comment by dneuman64** [comment]
What version of linux are you running?  Do you have HOSTNAME in /etc/sysconfig/network?

**Comment by dneuman64** [comment]
Also, as far as I know, `/opt/traffic_monitor/bin/traffic_monitor_config.p`l doesn't run as part of the install.

**Comment by smalenfant** [comment]
The `traffic_monitor_config.pl` doesn't run part of install. I guess it failed my Ansible playbook for Traffic monitor installation.

```
# cat /etc/sysconfig/network
NETWORKING=yes
HOSTNAME=
```

**Comment by dneuman64** [comment]
Yeah, you might just want to have Ansible update that file.  I dont think this is a bug...

**Comment by smalenfant** [comment]
Can I ask the question why we are relying on /etc/sysconfig/network? `hostname -fqdn` should hold the problem information.

**Comment by smalenfant** [comment]
@dneuman64 Please review what I proposed. Basically something without using /etc/sysconfig/postinstall.

**Comment by smalenfant** [comment]
I also noted that `domain_name` is not used.

**Comment by dneuman64** [comment]
will take a look and chat it over with the team.  What's interesting is that you should have had the same problem in previous releases, we just added more defensive coding...

**Comment by smalenfant** [comment]
Since `domain_name` was not used as well, not failing. `hostname -s` was working just fine for `host_name`

```
$global->{'host_name'} = $hostname_short;
```

**Comment by smalenfant** [comment]
Looks like the previous error was a warning. So it's been complaining, but not failing... Forcing me to read on Perl...
