### ISSUE TITLE
Traffic Ops doesn't allow for active/standby configuration in Multi Site Origin.

### ISSUE THREAD

**Issue by knutsel** [Comcast/traffic_control#1344]
Thought there was an issue on this already, but can't find it... This is needed for the redundant  linear video origin setup

See code starting @ https://github.com/Comcast/traffic_control/blob/master/traffic_ops/app/lib/UI/ConfigFiles.pm#L1088 and line 1100 

We are hardcoded to `round_robin=consistent_hash`

for active/standby, we need `round_robin=false`

@limited - is this something you guys are going to do??? (referring to our email convo)... Any idea on when?

**Comment by limited** [comment]
In progress as we speak.

**Comment by knutsel** [comment]
Don't know why we can't assign weinfensh, will ask around.

**Comment by mtorluemke** [comment]
Added weifensh as a "collaborator" to the project, now we can assign.

**Comment by jrushford** [comment]
Jan,

There are actually four possible values for ‘round_robin’.  Should traffic ops not support all four?  Here are the possible values for ‘round_robin’:


  *   ‘false’ - The first parent is always chosen if marked available.  Other parents in the list are chosen if the first selected parent is unavailable or if there is a connection error, then another parent is chosen to retry the transaction.
  *   ‘true’ - Parents are chosen using on modulus arithmetic of the client IP.  As above, if the first chosen parent is unavailable or if there is a connection error, another parent is chosen to retry the transaction.
  *   ‘strict’ - Parents are chosen in strict round robin fashion.  As above, if the first chosen parent is unavailable or if there is a connection error, another parent is chosen to retry the transaction.
  *   ‘consistent_hash’ - Parents are chosen from a consistent hash ring based upon a hash of the request url.  As above, if the first chosen parent is unavailable or if there is a connection error, another parent is chosen to retry the transaction.

Thanks
--
John J. Rushford
IPCDN Engineering
1400 Wewatta Street, Denver Colorado 80202
John_Rushford@cable.comcast.com

**Comment by jianli123** [comment]
The design of Multi Site Origin Design For Algorithm Primary/backup is ready at https://docs.google.com/document/d/1TAo2jBZqdb8TY9Tn_Kjn1zYm7XHt5jhQnt1AvBK8eO0/edit?usp=sharing and please take a look.  And the code will come soon. thanks

**Comment by smalenfant** [comment]
Is there anyway we can get away from the single profile per origin? Could we separate the "cache server assignment" from the "origin server assignments"?

Create a new table called "deliveryservice_origin" and assign ranks in that table for example. This might also open some option regarding origin servers assignements. 

For example, I would like to be able to specify "routes" to get to an origin in the future.. Would be nice to specify Origin with Mid neighbors. 

Example: Origin is in Atlanta region and I have 3 Mid-Cache groups. I'd like to tier my Mids (or my edges if needs be).

Atlanta Edge -> Atlanta Mid -> Atlanta Origin
North East Edge -> North East Mid -> Atlanta Mid -> Atlanta Origin
West Edge -> West Mid -> Atlanta Mid -> Atlanta Origin

**Comment by weifensh** [comment]
@smalenfant Thanks for your comments. Use a separated "origin server assignments" looks to be a better way to assign the origin servers and define their "ranks". The current implementation tries to make less changes on traffic_ops. Maybe we could enhance this in future?

**Comment by weifensh** [comment]
@jrushford Hi John, so far only two types of "round_robin" policies are added: "consistent_hash" and "false". If the other two are also needed, I could add it.

**Comment by knutsel** [comment]
I am +1 on adding the others? Since we're in there anyway?

**Comment by jrushford** [comment]
I guess those two are fine for now.  We can add the others if and when needed.

Thanks
--
John J. Rushford
IPCDN Engineering
1400 Wewatta Street, Denver Colorado 80202
John_Rushford@cable.comcast.com

**Comment by jrushford** [comment]
+1 on adding them now.

Thanks
--
John J. Rushford
IPCDN Engineering
1400 Wewatta Street, Denver Colorado 80202
John_Rushford@cable.comcast.com

**Comment by weifensh** [comment]
So adding the extra 2, pull request is #1377
