### ISSUE TITLE
TO: Inconsistent edge parent.config configuration using secondary parent

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#1349]
I have the following configuration in Traffic Ops :

| cache-group | primary parent | secondary parent |
| --- | --- | --- |
| vm-cdn1-east-edge | vm-cdn1-east-mid | vm-cdn1-west-mid |
| vm-cdn1-west-edge | vm-cdn1-west-mid | vm-cdn1-east-mid |

Edge configuration is inconsistent from both a parent/secondary perspective and IP/names.
- `dest_domain=origin.services.coxlab.net` has the proper parents and using IPs.
- `dest_domain=.` has all the parent in the same exact group. Also, it is using DNS names instead of IPs. This seems to be there since the beginning.
- I feel like I'm missing a parameter, but this configuration here doesn't look consistent.

```
dest_domain=origin.services.coxlab.net parent="68.1.14.137:80|0.999;68.1.14.138:80|0.999;68.1.14.152:80|0.999;" secondary_parent="68.1.14.153:80|0.999;68.1.14.154:80|0.999;68.1.14.155:80|0.999;" round_robin=consistent_hash go_direct=false qstring=ignore
dest_domain=. parent="cdn1cdmid0001.coxlab.net:80|0.999;cdn1cdmid0002.coxlab.net:80|0.999;cdn1cdmid0003.coxlab.net:80|0.999;cdn1cdmid0004.coxlab.net:80|0.999;cdn1cdmid0005.coxlab.net:80|0.999;cdn1cdmid0006.coxlab.net:80|0.999;" round_robin=consistent_hash go_direct=false qstring=ignore
```

**Comment by smalenfant** [comment]
@knutsel FYI

**Comment by MattMills** [comment]
Moved to https://issues.apache.org/jira/browse/TC-313
