### ISSUE TITLE
Purge requests automatically queue updates

### ISSUE THREAD

**Issue by lwickline** [Comcast/traffic_control#1357]
There should be a mechanism to disable the auto queue updates when a customer issues a purge request so that we can do maintenance without updates happening in an uncontrolled manner.

This should include messaging to the customer that we are in a maintenance cycle and a the execution of any purges when we come out of the maintenance cycle

**Comment by knutsel** [comment]
I propose we take the regex_revalidate.config distribution out of the ort / syncds process, and kick off a ansible workbook to scp the file to all caches (mids first, then edges), when it is updated. There is no traffic_line -x needed for an update to this file.

**Comment by knutsel** [comment]
and i porpose we don't do this.

**Comment by mitchell852** [comment]
sounds like there have been some requests to speed up purge anyhow. per what @knutsel said, maybe that would help speed it up (rather than having to wait 15 minutes for ort)

**Comment by limited** [comment]
If using ansible, how will the ssh key management work? 

Will we need to manually provision a passwordless ssh key with root access on all of our caches that we might want to purge on?

**Comment by knutsel** [comment]
Yes. We use puppet to push out the keys and take it from there.

**Comment by limited** [comment]
1) If you already use Puppet for managing SSH keys, why bring another tool (Ansible) into the mix?

2) I think we'll likely take another route for distributing the regex_revalidate.conf file, but am not sure what that route will be. To whatever extent we can make this mechanism modular would be very much appreciated. I'll be sure to review the eventual PR with this in mind too.

**Comment by lwickline** [comment]
ansible allows for add hock commands to be sent to specific servers/groups of servers. Puppet just updates configurations on a polling schedule. While you could come up with a way to do this in puppet it will be much more fragile and difficult to maintain. 

You also will get back immediate success/failure results with ansible where with puppet you would have to build something to parse logs. 

The both perform a similar role but they way the approach the problem is different.  If you wanted to remove puppet from the equation you could just build the user and key into the iso image but there is a chicken and egg issue with getting the the management accounts on the servers.  We currently already maintain keys in puppet so adding one more is easy.

**Comment by smalenfant** [comment]
We manage ssh keys with Ansible (when we first deploy the servers). For us it's a non-issue for Ansible.
