### ISSUE TITLE
More robust geo-blocking solution

### ISSUE THREAD

**Issue by mtorluemke** [Comcast/traffic_control#1364]
Currently, we can geo-block based on:
1. CZF only
2. CZF + US
3. CZF + CA

We should have a more robust solution -- for instance some territories show up in the geo DB as part of a different country.

**Comment by limited** [comment]
Hey Mark-
  We can also geo-block on Postal Code on a per-url basis. So far we've only tested it on Canadian postal codes, but no reason it shouldn't work for other countries. We also support whitelisting/blacklisting of specific IPs/subnets. 

More details here: https://github.com/Comcast/traffic_control/wiki/Regional_Geoblocking

We're actively using this in production today and would be interested in discussing enhancements to this area

**Comment by rob05c** [comment]
Geo-blocking can now accept a comma-separated list of countries.
