### ISSUE TITLE
Unable to export profile with no parameters

### ISSUE THREAD

**Issue by elsloo** [Comcast/traffic_control#137]
When attempting to export a profile with no parameters, the following error is displayed:

```
Traffic Ops fatal error occurred while processing your request. 
Error at line 387 (    my $text = JSON->new->utf8->encode($jdata);) 
hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at /opt/traffic_ops/app/script/../lib/UI/Profile.pm line 387.
```

This stems from the query on line 372 that looks only at the profile parameter table in order to build the data structure that is marshalled to JSON on line 387.

We can fix this quickly by not allowing a parameterless profiles to be exported, or fix it thoroughly to support both cases (more time consuming and requires touching the import code as well).

**Comment by knutsel** [comment]
why would you want to export a profile with no parameters?

**Comment by elsloo** [comment]
Our Riak profiles have no parameters, which I was unaware of when I attempted to export the profile.  If we don't want to export a parameterless profile then we should provide a meaningful message instead of barfing.  I write a quick fix to do that if it's preferable over allowing the export to proceed without parameters.
