### ISSUE TITLE
TC: Ansible Inventory Script

### ISSUE THREAD

**Issue by jheitz200** [Comcast/traffic_control#1378]
Write a script to gather host information from Traffic Ops. This host list will be used to deploy Ansible Playbooks.

**Comment by smalenfant** [comment]
Do you have anything started on this? We do have something in both Perl and something Python started. 

Adding @hbeatty

**Comment by jheitz200** [comment]
@smalenfant I have started to write it in Go but we are still working out some of the organizational details.  I'll let you know when I have it at a point where you can test it and let me know your feedback if you like

**Comment by hbeatty** [comment]
@jheitz200 You don't want to use what we already have?

**Comment by jheitz200** [comment]
@hbeatty I would love to take a look at it

**Comment by hbeatty** [comment]
@jheitz200 OK. I'll clean it up and get it posted. Should have something for you to look at tomorrow morning.

**Comment by hbeatty** [comment]
@jheitz200 Steve and I wrote a traffic-control-python package and I put the dynamic inventory in there. https://github.com/hbeatty/traffic-control-python/blob/HB-dynamic-inventory/docs/examples/traffic-ops.py. traffic-control-python requires python-requests (yum install -y python-requests). Once you've cloned the repo you can copy the traffic-ops.py to the root of the repo to test. You'll also need to update the url and token on line 62.

We are going to move the token and url out of there but, haven't gotten that far yet.

Let me know if you have any questions.
