### ISSUE TITLE
ORT syncds bug

### ISSUE THREAD

**Issue by jpappa200** [Comcast/traffic_control#1380]
A parent from a different CDN can hold up a child from running syncds if Traffic Ops has multiple CDN's configured.

https://<to_host>/update/<host> looks at all parents associated with the cache group and doesn't check which CDN it's associated with.

**Comment by jeffmart** [comment]
1. Is this hold up indefinite?
or 
2. does syncds complete on the child after all parents for all CDNs in that cache group are updated?

I am assuming #2 but want to make sure.

**Comment by knutsel** [comment]
so we have a issue somewhere to take regex_revalidate out of the ort/syncds distribution mechanism, and scp (or ansible dist) it directly on update; this would remove the "mids have to complete ort syncds before edges" requirement, and things should get a lot better when we do that...

**Comment by knutsel** [comment]
Can't find the issue... I'll make this the issue for it.

**Comment by knutsel** [comment]
See also #513

**Comment by nir-sopher** [comment]
Moved to: https://issues.apache.org/jira/browse/TC-317
