### ISSUE TITLE
TO: traffic_ops postinstall issue

### ISSUE THREAD

**Issue by kailuocisco** [Comcast/traffic_control#1386]
The following code is copied from "traffic_ops/install/bin/postinstall":

        # write whole config to temp file
        my $tmpfile = File::Temp->new();
        print $tmpfile $dumper->Dump();
        close $tmpfile;

        # rename current config file to something unique so it's not lost
        my $backup_num = 0;
        my $backup_name;
        do {
                $backup_num++;
                $backup_name = "$cdn_conf.backup$backup_num";
        } while ( -e $backup_name );
        rename( $cdn_conf, $backup_name ) or die("rename(): $!");

The rename() will fail if the directory "/tmp/" and the directory "traffic_ops/install/bin/" are not in the same disk partition.

The same issue will be found in the script "traffic_ops/install/bin/generateCert"

**Comment by dangogh** [comment]
good catch!  I think File::Copy::move should handle that better..
