### ISSUE TITLE
Misleading Statistics

### ISSUE THREAD

**Issue by elsloo** [Comcast/traffic_control#139]
Improve Traffic Router routing statistics to remove existing ambiguity.  For a specific example, when a client makes a request and is matched in the CZF but the desired delivery service is not available in that cache group (assignment, limits, availability, etc), the request is serviced by the closest available cache group.  This results in a GEO tally, which is also incremented in the case where we had a CZF miss and performed a MaxMind geo lookup on the IP address.

We need more granularity to describe our various HIT/MISS scenarios such that we know exactly what is happening with our routing decisions.  We may also want to refactor where/how we set the ResultType, as miss scenarios are handled both in TrafficRouter and DeliveryService.

**Comment by elsloo** [comment]
Coordinate changes w/portal.

**Comment by mitchell852** [comment]
This is no longer relevant.
