### ISSUE TITLE
Traffic Ops RPM built on CentOS 7 fails to make install/bin files executable

### ISSUE THREAD

**Issue by rob05c** [Comcast/traffic_control#1414]
Notably, postinstall, install_web_deps, and goose.

This means a user has to manually `chmod +x` those files to run `postinstall`. Moreover, it breaks the Dockerfile.

**Comment by robert-butts** [comment]
Looks like this only affects RPMs built on CentOS 7, so, increasing the milestone.

It looks like there are other issues with RPMs built on CentOS 7, so maybe we should make a single case, "fix RPM building for CentOS 7."

**Comment by jianli123** [comment]
Is the 1.8.0 milestone to support CentOS 7?

**Comment by robert-butts** [comment]
@jianli123 Not in particular, I just set the milestone to an arbitrary future date.

Do you need CentOS 7 support? If there's a community need, we can think about increasing the priority.

**Comment by jianli123** [comment]
Yes, we need CentOS 7 support. And actually we see the performance and security benefit from CentOS 7 compared with 6.x, so could you help increasing the priority for CentOS7.x?  thanks

**Comment by limited** [comment]
Maybe we could work together on the upgrade to Centos7? If we created a shared list of tasks that need attention, we could divide and conquer?

**Comment by dangogh** [comment]
@limited -- great idea..   First thing needed is knowing what the issues are.   Anyone interested in getting it to happen,  try installing (or running dev environment) on CentOS 7 and report any issues.  Different issues should be reported separately, though so it's easy to divide the work.

**Comment by dangogh** [comment]
No longer an issue in 1.8.0 -- closing.
