### ISSUE TITLE
ORT 1.5.0: FATAL on regex_revalidate.config returned HTTP 404!

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#1435]
There is a FATAL error in ORT 1.5.0 when there is no active revalidation. Makes syncds and badass mode fail. 

This was run in `badass` mode :

```
FATAL https://traffic-ops.kabletown.net/Trafficserver-Snapshots/tve/regex_revalidate.config returned HTTP 404!
[root@mid ~]#
```

**Comment by knutsel** [comment]
this will get fixes when we fix #1357.

**Comment by smalenfant** [comment]
Example from 0.53c ORT which works fine.

```
[root@dukecdmid07 ~]# /opt/ort/traffic_ops_ort.pl badass warn https://dukecdcms0002.rd.at.cox.net chs:w@term@rk -dispersion=1
Fri May 20 12:38:43 UTC 2016
Version of this script: 0.53c
WARN Sleeping for 4 seconds: ....
ERROR Deleting directories older than 1463143123
ERROR Received error code 404 for https://traffic-ops.kabletown.net/Trafficserver-Snapshots/tve/regex_revalidate.config from Traffic Ops!
ERROR Result from curling https://traffic-ops.kabletown.net/Trafficserver-Snapshots/tve/regex_revalidate.config is HTTP 404!
ERROR Received error code 404 for https://traffic-ops.kabletown.net/Trafficserver-Snapshots/tve/regex_revalidate.config from Traffic Ops!
ERROR Result from curling https://traffic-ops.kabletown.net/Trafficserver-Snapshots/tve/regex_revalidate.config is HTTP 404!
```

**Comment by smalenfant** [comment]
I upgraded to `traffic_ops_ort-1.6.0-3500.9d1ef9d1`. Just confirming this is still present with #1357 fixed.

**Comment by smalenfant** [comment]
What is that `Trafficserver-Snapshots` path? Is this still required? 

Seems like the current path is `/genfiles/view/<hostname>`

**Comment by smalenfant** [comment]
Alright... By default when you install Traffic Ops and have the `regex_revalidate.config` location, you need to either 

1) touch the `/opt/traffic_ops/app/public/Trafficserver-Snapshots/<cdn>/regex_revalidate.config` file
2) Invalidate some funky content so the file is created

Not sure what the real fix is. Not sure the install and/or Traffic Ops startup could create those files.

I believe this parameter is installed by default as well :

`json/profile_parameter.json:{"profile":"EDGE1_CDN_520","parameter":"location","config_file":"regex_revalidate.config","value":"/opt/trafficserver/etc/trafficserver"}`

**Comment by limited** [comment]
Now generated in real-time
