### ISSUE TITLE
In the traffic ops API, cache group health is not sorted correctly

### ISSUE THREAD

**Issue by mitchell852** [Comcast/traffic_control#144]
Regarding this api endpoint: /api/1.1/cdns/health.json

cache groups should be sorted from unhealthiest to healthiest where health = online / (online + offline) and then alphabetically.

**Comment by knutsel** [comment]
Why not do the sorting on the API consumer?

**Comment by mitchell852** [comment]
yea, i can be sold on that. i wrote this issue up because i *thought* it was sorting that way at one time...

i'll close the issue.
