### ISSUE TITLE
The "type" for "edge_atl_group" isn't correct in database

### ISSUE THREAD

**Issue by jifyang** [Comcast/traffic_control#1442]
In traffic ops database, the "type" for "edge_atl_group" should be "5". The detail is as following:

mysql> use to_test;
Database changed
mysql> select id, name, type from cachegroup;
+----+---------------------+------+
| id | name                | type |
+----+---------------------+------+
|  3 | edge_atl_group      |    1 |
|  1 | mid-northeast-group |    2 |
|  2 | mid-northwest-group |    2 |
+----+---------------------+------+
3 rows in set (0.00 sec)

mysql> select \* from type where id=1 or id=5;
+----+----------+-----------------+--------------+---------------------+
| id | name     | description     | use_in_table | last_updated        |
+----+----------+-----------------+--------------+---------------------+
|  1 | EDGE     | Edge Cache      | server       | 2016-05-23 12:20:15 |
|  5 | EDGE_LOC | Edge Cachegroup | cachegroup   | 2016-05-23 12:20:15 |
+----+----------+-----------------+--------------+---------------------+
2 rows in set (0.00 sec)

mysql>

**Comment by dg4prez** [comment]
Fixed in 2.1.
