### ISSUE TITLE
Traffic Router fetches invalid czfile/rgbfile to its db directory

### ISSUE THREAD

**Issue by weifensh** [Comcast/traffic_control#1449]
If the parameter "coveragezone.polling.url" of TR points to an invalid coveragezone file, TR still downloads it to its local db directory. When TR restarts, there will be no valid coveragezone file to use.

A possible fix is not to download invalid files to local db. Thus TR could use the latest valid config file.

**Comment by dneuman64** [comment]
This was fixed by #1748
