### ISSUE TITLE
postinstall: r154 version of jquery.flot.axislabels not available anymore

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#1451]
From postinstall of 1.5.1 :

`Got HTTP 404 response for 'https://gflot.googlecode.com/svn-history/r154/trunk/flot/jquery.flot.axislabels.js'`

**Comment by mitchell852** [comment]
This is a duplicate of #1453 which has been fixed.

**Comment by dangogh** [comment]
fixed by #1454
