### ISSUE TITLE
How to config Traffic Ops HTTP Delivery Service correctly with Traffic Router?

### ISSUE THREAD

**Issue by chiconguyen2601** [Comcast/traffic_control#1497]
Please help me to config correctly the HTTP Delivery Service, I use values as below, but Traffic Router is not working (**return 503**) when I request: tr.movies.c23.example.net
[https://drive.google.com/file/d/0B7gZlR68iL5jbWcxMmJuUXlmeXM/view?usp=sharing](https://drive.google.com/file/d/0B7gZlR68iL5jbWcxMmJuUXlmeXM/view?usp=sharing)

**Comment by lwickline** [comment]
Is your trafficrouter running and properly delegated in dns?
The URL for that delivery service per your images is :

ccr.movies.c23.phamminhluan.tk


curl -Lvsk http://ccr.movies.c23.phamminhluan.tk
* Rebuilt URL to: http://ccr.movies.c23.phamminhluan.tk/
* Could not resolve host: ccr.movies.c23.phamminhluan.tk
* Closing connection 0

**Comment by dneuman64** [comment]
Also, we have a google group that is great for asking questions and gettting help, you might want to try there:  https://groups.google.com/forum/#!forum/traffic_control

**Comment by chiconguyen2601** [comment]
Hi lwickline,

The URL for HTTP delivery service is: 
**tr.movies.c23.phamminhluan.tk**, the URL in my images is only the example url.

The trafficrouter, I build and run it from source. But, maybe it's not working when I request HTTP delivery service, it return **503 code**.

```
 curl -Lvsk http://tr.movies.c23.phamminhluan.tk
* STATE: INIT => CONNECT handle 0x600057820; line 1402 (connection #-5000)
* Rebuilt URL to: http://tr.movies.c23.phamminhluan.tk/
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => WAITCONNECT handle 0x600057820; line 1455 (connection #0)
* Connected to tr.movies.c23.phamminhluan.tk port 80 (#0)
* STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x600057820; line 1562 (connection #0)
* STATE: SENDPROTOCONNECT => DO handle 0x600057820; line 1580 (connection #0)
> GET / HTTP/1.1
> Host: tr.movies.c23.phamminhluan.tk
> User-Agent: curl/7.49.0
> Accept: */*
>
* STATE: DO => DO_DONE handle 0x600057820; line 1659 (connection #0)
* STATE: DO_DONE => WAITPERFORM handle 0x600057820; line 1786 (connection #0)
* STATE: WAITPERFORM => PERFORM handle 0x600057820; line 1796 (connection #0)
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 503 Service Unavailable
< Content-Type: text/html;charset=ISO-8859-1
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Length: 1385
* Server Jetty(7.6.3.v20120416) is not blacklisted
< Server: Jetty(7.6.3.v20120416)
<
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 503 Service Unavailable</title>
</head>
<body><h2>HTTP ERROR 503</h2>
<p>Problem accessing /. Reason:
<pre>    Service Unavailable</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>                                          
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

</body>
</html>
* STATE: PERFORM => DONE handle 0x600057820; line 1955 (connection #0)
* multi_done
* Connection #0 to host tr.movies.c23.phamminhluan.tk left intact
* Expire cleared
```

The output log in TrafficRouter is below: 
**traffic_control.traffic_router.core.access: 1465395519.553 qtype=HTTP chi=113.161.99.16 url="http://tr.movies.c23.phamminhluan.tk/" cqhm=GET cqhv=HTTP/1.1 rtype=DS_MISS rloc="-" rdtl=- rerr="-" rgb="-" pssc=503 ttms=2 rurl="-" rh="-"**

I dont know why, maybe I'm wrong to config HTTP delivery service on TrafficOps. Please help me, thank you so much!
