### ISSUE TITLE
Traffic Router HTTP Redirection to HTTPS

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#1505]
Discussions as started on adding HTTPS to Traffic Router and we have a specific use case for Video Delivery service over HTTPS. This could be either enhancement or question.

The need would be to use HTTP and HTTPS as a request method to Traffic Router, but the redirection would always end up being an HTTPS location. Since this is for video delivery, we want to keep the Request Routing to minimal delay, keeping resource usage on the Client/Server low.

Seems like this should be the default behavior. 

Somewhat related to #1457 although this is Edge server requirement, which this here is kind of a similar ask except done at the Traffic Router.

**Comment by jianli123** [comment]
@smalenfant  do you have any plan when it will be ready?

**Comment by limited** [comment]
I don't think Steve is working on this feature. I think its probably Dave Neuman who is writing the code. I talked to Jeff last week and he let me know an ETA of end of July.

**Comment by dneuman64** [comment]
We are definitely aiming to have a "beta" version of it ready by the end of July.  We are planning on including this functionality in the 1.7 release which is scheduled for end of August.  If you are interested in helping us test this functionality let me know and I can make sure to get you a pre-release version when it is ready.

**Comment by limited** [comment]
Does v1.7 == v2.0?

**Comment by dneuman64** [comment]
Yeah, sorry, I forgot about the bump to 2.0 for the release after 1.6.
