### ISSUE TITLE
TO API: deliveryservice_stats.json?metricType=tps_total returns aggregate transactions not tps

### ISSUE THREAD

**Issue by mitchell852** [Comcast/traffic_control#1528]
/api/1.2/deliveryservice_stats.json?deliveryServiceName=foo&metricType=tps_total...

^^ this api call returns aggregate transactions per minute not tps (per second), therefore, to get tps the returned values need to be divided by 60.

**Comment by mitchell852** [comment]
The influx query is built in series_query() - https://github.com/Comcast/traffic_control/blob/master/traffic_ops/app/lib/Extensions/TrafficStats/Builder/DeliveryServiceStatsBuilder.pm#L74

the influx query needs to be more like mean(value)/60

.. but be careful, this is a method used for more than tps...

**Comment by dneuman64** [comment]
we should verify what _astats and traffic monitor are doing.  It is possible that they are already doing this math and our rollups are simply an average of the tps for 1 minute, which would mean we wouldn't want to /60.

**Comment by elsloo** [comment]
tps_total is created by Traffic Monitor by calculating tps_2xx, tps_3xx, tps_4xx, and tps_5xx, then summing all for the final value. The TPS is calculated by taking the current tps_Nxx, subtracting the prior tps_Nxx and dividing by the polling interval delta. tps_Nxx comes from the astats status_Nxx fields, which is a simple counter.

**Comment by mitchell852** [comment]
What has been throwing me off is the high values coming back from a tps_total influx query like this:

SELECT value FROM "deliveryservice_stats"."monthly"."tps_total.ds.1min" WHERE deliveryservice = 'foobar' AND cachegroup = 'total' AND time > now() - 1h limit 100;

but looking closer at each query that contributes to tps_total (2xx, 3xx, 4xx, 5xx), it is clear that the tps_5xx results are the cause of the high values:

SELECT value FROM "deliveryservice_stats"."monthly"."tps_2xx.ds.1min" WHERE deliveryservice = 'foobar' AND cachegroup = 'total' AND time > now() - 1h limit 100;

^^ 2xx seems fine

SELECT value FROM "deliveryservice_stats"."monthly"."tps_3xx.ds.1min" WHERE deliveryservice = 'foobar' AND cachegroup = 'total' AND time > now() - 1h limit 100;

^^ 3xx seems fine

SELECT value FROM "deliveryservice_stats"."monthly"."tps_4xx.ds.1min" WHERE deliveryservice = 'foobar' AND cachegroup = 'total' AND time > now() - 1h limit 100;

^^ 4xx seems fine

SELECT value FROM "deliveryservice_stats"."monthly"."tps_5xx.ds.1min" WHERE deliveryservice = 'foobar' AND cachegroup = 'total' AND time > now() - 1h limit 100;

^^ 5xx seems to be the culprit. getting some real high values.

With all that said, I believe the cause of the 5xx numbers can be attributed to the astats bugs filed here so i will close this:

https://issues.apache.org/jira/browse/TS-3361
https://issues.apache.org/jira/browse/TS-3948
