### ISSUE TITLE
TO API: urlkeys endpoint returning a HASH

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#1529]
I was trying to automate url key extractions from TO, although looks like this API doesn't return the content I was expecting. This might not be a documented API either. 

```
https://to.kabletown.net/api/1.2/deliveryservices/xmlId/test_ds/urlkeys.json
{"response":"HTTP::Response=HASH(0x7ecc440)"}
```

**Comment by limited** [comment]
https://issues.apache.org/jira/browse/TC-323
