### ISSUE TITLE
ToPingCheck.pl extension script does not work for 10G6 or iLO

### ISSUE THREAD

**Issue by limited** [Comcast/traffic_control#153]
The selection of IP address to use is done via the select JSON property. If select is not provided,  the 10G IPV4 ipAddress is used. When select is provided, it must be in the form of an array. The first two values in that array are used to lookup the address to ping:
$ip = $server->{ $select->[0] } . "." . $server->{ $select->[1] };

This works well for FQDN, as you can set select to ["hostName", "domainName"]. When trying to select either ip6Address or iloIpAddress, the address to ping has a period appended to end it, causing the ping to fail.

Additionally, for IPv6: The ping6 command should be used instead of ping.

**Comment by knutsel** [comment]
the code at https://github.com/Comcast/traffic_control/blob/master/traffic_ops/app/bin/checks/ToPingCheck.pl#L75 uses the concat when it is an array, but just the field when it's not.. Not sure I understand that part of this bug.

**Comment by knutsel** [comment]
Fix incoming for IPv6. Be sure to have this as your params in the checks:

IPv4; -c '{ "check_name": "10G", "select": "ipAddress", "base_url": "https://127.0.0.1" }'
IPv6: -c '{ "check_name": "10G6", "select": "ip6Address", "base_url": "https://127.0.0.1" }'
