### ISSUE TITLE
Request for traffic ops feature to show info on why a server is either admin_down or offline.

### ISSUE THREAD

**Issue by jdawgitsome** [Comcast/traffic_control#1542]
Request for traffic ops to show info on why a server is either admin_down or offline.
For example: User bob has set admin_down on server xtream-ats-01.  Prior to admin_down and queueing, on the pop up box add a notes area that can be viewable after where a user can place information as to why the server is being set this way.  Also include a section as to what user is making the change.  Possibly do not allow admin down or offline to proceed without comment.

**Comment by CDNOPS** [comment]
How can we get this request prioritized?  The fact that we do not know at a glance why hosts are off-lined is causing a ton of pain and unnecessary investigations for the operations team.  Please advise
