### ISSUE TITLE
Backup the CDN system!

### ISSUE THREAD

**Issue by chiconguyen2601** [Comcast/traffic_control#1546]
Hi,

How to restore the CDN system when the Traffic Router die? 

Please help me to resolve this trouble. Thanks so much!

**Comment by smalenfant** [comment]
Just as a note, I think simply re-installing traffic router would do the trick. Although if you only have a single traffic router, that's probably not suggested.

**Comment by chiconguyen2601** [comment]
I'm sorry. My english is not clear. I mean how to build a system with many Traffic Routers run at same time???
In the case, any Traffic Router die, the other still work, my CDN system is still alive.

**Comment by dneuman64** [comment]
It's ok, thanks for clarifying.  We actually recommend that you run with more than one Traffic Router.  All you really need to do is install and configure as many traffic routers as you want.  I think the most important configuration is to update `traffic_monitor.bootstrap.hosts` in  `/opt/traffic_router/conf/traffic_monitors.properties` to point to your traffic monitors.  If you have multiple traffic monitors (we recommend you do) you can configure more than one by seperating the traffic monitor hosts with a semi-colon  (e.g. `traffic_monitor.bootstrap.hosts=tm-01.kabletown.net:80;tm-02.kabletown.net`).  You will also probably want to update `traffic_ops.username` and `traffic_ops.password` in `/opt/traffic_router/conf/traffic_ops.properties`.  For other configuration information see here:  http://traffic-control-cdn.net/docs/latest/admin/traffic_router.html#configuring-traffic-router.  Give that a try and let me know if you have any more questions.

**Comment by dneuman64** [comment]
Hey @chiconguyen2601 is this issue resolved?  If so, i will close this issue.

**Comment by chiconguyen2601** [comment]
Hi dneuman64,

This issue is resolved. Thank you so much for your answer.
