### ISSUE TITLE
Enhance DNSSEC Key API

### ISSUE THREAD

**Issue by elsloo** [Comcast/traffic_control#156]
Enhance the DNSSEC key API as follows:

* Each key type should be an array of keys rather than a single key object
* Key generation should occur at (current key expiration - (max TTL * $generation_multiplier)), where:
  * max TTL is the maximum global TTL for the CDN TLD, or the same for the delivery service
  * If a TTL for a given type does not exist, Traffic Router will use the TTL from the global (CDN TLD) settings when building the zone for the delivery service
  * $generation_multiplier should default to something like 10, but we should support this through a parameter assigned to the Traffic Router profile
* Introduce a new field on the key object called effectiveDate, which should be calculated based on expiry of existing keys, or a user supplied date/time
  * effectiveDate, when calculated on the fly, should be (current key expiration - (max TTL * $effective_multiplier)), where:
    * $effective_multiplier should default to no less than 2
    * max TTL should be computed using the same method used above

**Comment by dneuman64** [comment]
- Updated the record stored in traffic vault to contain an array of keys for KSK and ZSK.
    - Added a status field to the keys stored in traffic vault ('new' for new keys and 'expired' for expired keys)
        - Use this key to determine which key to check for expiration ('new' key).
        - If key is expired set it to 'expired' and add back to array with new key
   - Updated 
     - Need to add a new parameter named ‘tld.ttls.DNSKEY’ to Traffic Router profile to define TTL.  Otherwise will default to 60(s).
     - Need to add a new parameter named:  'DNSKEY.generation.multiplier’ to Traffic Router profile to define expiration multiplier.  Otherwise code will default to 10.
Introduce a new field on the key object called effectiveDate, which should be calculated based on expiry of existing keys, or a user supplied date/time
     - Need to add a new parameter named: ‘DNSKEY.effective.multiplier’ to Traffic Router profile
