### ISSUE TITLE
How to config to monitor Origin sites in TrafficMonitor page?

### ISSUE THREAD

**Issue by chiconguyen2601** [Comcast/traffic_control#1580]
Hi,

As title, I want to know clearly step by step to config TrafficOps and TrafficMonitor can monitor healthy of Origin Server? I installed ATS in Origin Server, but I can not config for TrafficOps and TrafficMonitor getting healthy from Origin Server? Please help me. Thank you so much!

P.s: I'm sorry, I have to post this question to here, because I can not post it to https://groups.google.com/forum/#!forum/traffic_control.

**Comment by dneuman64** [comment]
Traffic Monitor currently only monitors the status of EDGE and MID servers that are set to REPORTED.
