### ISSUE TITLE
need a way to configure qstring value in parent.config by DeliveryService

### ISSUE THREAD

**Issue by dneuman64** [Comcast/traffic_control#1584]
Currently the qstring value in the parent.config is based on a parameter on the server profile.  We need to make this configurable so that the qstring can be set to "consider" if we want the qstring to be used when hashing to a parent.

**Comment by smalenfant** [comment]
The proposal here would be to set the parent.config line to `qstring=consider` when the Query String Handling == 0 (use qstring in cache key, and pass up). 

I got a patch I'm testing in my lab.

**Comment by dneuman64** [comment]
yeah, that is the same idea I had.  I dont know if it is perfect but it is good enough
