### ISSUE TITLE
Traffic Ops Extensions RTR and MTU not in correct columns

### ISSUE THREAD

**Issue by limited** [Comcast/traffic_control#159]
On the Health->Server Check page, the icons for RTR and MTU are either not appearing, or not appearing in the correct columns.

Details:
Checking the to_extension table, MTU is id=11 with shortname "ak". RTR is id=12 with shortname="al". Both are active and have type=CHECK_EXTENSION_BOOL. 

When Mojolicious renders the server_check page, it is inserting MTU into column 16 and RTR into column 17. These values should actually be shifted 1 column to the left. 

Interestingly, the pattern of extensions in the database and rendered HTML is as follows:
`
Database-  {ILO, 10G, FQDN, DSCP, OPEN, OPEN, 10G6, OPEN, OPEN, OPEN, MTU, RTR, ...}
`
`
HTML-       {ILO, 10G, FQDN, DSCP, OPEN, OPEN, 10G6, OPEN, OPEN, OPEN, OPEN, MTU, RTR, ...}
`

Notice the extra OPEN line inserted somewhere between columns 12-15 that is not present in the database.

**Comment by knutsel** [comment]
Please try this: 

delete from to_extension where id=13;

There was a double "aj" in that table.. Will fix in the seed.

**Comment by knutsel** [comment]
actually, you also have to put the right column in: 

insert into to_extension (id,name, isactive, servercheck_column_name, type) values (13, 'OPEN', 0, 'am', 33);
