### ISSUE TITLE
TO: JSON::PP version unavailable on clean machine install

### ISSUE THREAD

**Issue by dangogh** [Comcast/traffic_control#1607]
During a clean install of traffic ops 1.6-RC6,  I see this:

```
Installing modules using /opt/traffic_ops/app/cpanfile
JSON::PP 2.27300 is not available
 at /opt/traffic_ops/app/local/lib/perl5/CPAN/Meta.pm line 301.
 at /opt/traffic_ops/app/local/lib/perl5/CPAN/Meta.pm line 301.
 at /usr/local/share/perl5/Carton/Snapshot.pm line 166.
```

Checking on possible solutions for this..

**Comment by dangogh** [comment]
turned out to be user error..

**Comment by smalenfant** [comment]
I've got the same problem on 1.6.0-RC6. What's my user error? Sorry, but re-opening.

```
Installing modules using /opt/traffic_ops/app/cpanfile
JSON::PP 2.27300 is not available
 at /opt/traffic_ops/app/local/lib/perl5/CPAN/Meta.pm line 301.
 at /opt/traffic_ops/app/local/lib/perl5/CPAN/Meta.pm line 301.
 at /usr/local/share/perl5/Carton/Snapshot.pm line 166.
WARNING: Failure to build required perl modules, check the output and correct the problem.
```

**Comment by dangogh** [comment]
well,   glad someone else saw it too..  There was a previous error in my setup which I thought had caused it,  but I'll rework it now.   Thanks..

**Comment by dangogh** [comment]
Another try -- I could not reproduce from a fresh 6.6 vm.

Also restarted with TO 1.5.1 and upgraded.   I saw the warning,  but saw no ill effect from it.

**Comment by smalenfant** [comment]
No ill effects on my side either... Wonder if that's just a CPAN thing.

**Comment by dangogh** [comment]
Closing since this is just a warning and seems to have no ill effect.
