### ISSUE TITLE
ORT: Update end point returning HTTP 500

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#1612]
Whenever the `syncds` is completed, seems like Traffic Ops ORT is getting a 500 errors from the update. The update does take place. 

```
ERROR Traffic Ops is signaling that an update is waiting to be applied.
ERROR Deleting directories older than 1468337149
ERROR start_service called for trafficserver.
ERROR trafficserver is running.
ERROR Traffic Ops is signaling that an update is ready to be applied, but none was found! Clearing update state in Traffic Ops anyway.
ERROR https://traffic-ops/update/edge0001 returned HTTP 500!
```

**Comment by mtorluemke** [comment]
Likely duplicate of #1238 -- reopen if not the case.

**Comment by hbeatty** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;PI3APZxT&#x2F;22-find-out-why-traffic-ops-ort-pl-is-returning-exit-code-1"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> find out why traffic_ops_ort.pl is returning exit code 1</a>
