### ISSUE TITLE
Proposed server table changes

### ISSUE THREAD

**Issue by dg4prez** [Comcast/traffic_control#1619]
1) Maximum hostname, domain name length - standards require these to be no longer than 63 bytes per segment.  Currently they're 45 char - suggest increasing to 63 for hostname, and 63 at minimum for domain name.  While domain name could technically be longer, i'd want some sort of safeguard built in to count per segment built into the ui before changing it.

2) Remove the unique requirement for host_name, ip_address, and ip6_address.  As long as we don't have identical profiles and cachegroups, we can still tell the difference between FQDN and we need a way to put the same servers into multiple groups for some MSO tricks, at least in the short term.  We may want to consider displaying the full FQDN in the server assignment list rather than just the host name.  This is also needed for host name because we've had requests to setup origins with the same hostname and different domain names.

3) Allow null values for interface name, ip_netmask, and ip_gateway.  When describing servers that we do not control such as origins, there's no need for this data and we end up fudging it.  Suggest changing the UI to require those fields when needed and allow the user not to enter them when they're not.  Relying on the database to block "bad" entries is bad design anyway and creates ugly errors that can't be recovered from without starting over.

**Comment by knutsel** [comment]
@limited : I remember you had the same problem with the uniqueness of ip address? Do I remember right? Does this fix your use case, or did you have something else in mind?

**Comment by limited** [comment]
Our use case was putting the same origin servers in two different CDNs. I think the above suggestion 2 would take care of our issue. We did discuss allowing dupe {hostname, ip_address, ip6_address} but with some type of popup warning box to the user. If thats not a ton of work I think it could still be useful.

**Comment by dg4prez** [comment]
if we could get the DB changed now and make the UI changes going forward, that would be terribly useful.

**Comment by dg4prez** [comment]
https://github.com/Comcast/traffic_control/pull/1623

**Comment by jeffmart** [comment]
I will second option number 2. We performed this in the DB, had done some initial testing. This is currently not in the code but given this is being brought up from another source is this something that we should re-review and consider? Note: right now we are using a VIP to work around this.

**Comment by dneuman64** [comment]
this was fixed by #1623

**Comment by mitchell852** [comment]
update on this:

1. done

2. unique constraint was removed from hostname but ip_address and ip6_address must be unique per profile.

3. not done due to the problems this would cause with edge and mid servers for example.
