### ISSUE TITLE
TO: Potential ipv6 issue with traffic_ops

### ISSUE THREAD

**Issue by dangogh** [Comcast/traffic_control#1621]
traffic_ops 1.6-RC6 installed on an internal test server is configured to listen on the ipv6 address: `listen => [ https://[::]:443?cert=.... ]`,   but traffic_ops would not start -- no error in the log file, but `hypnotoad` would not produce the `/var/run/traffic_ops.pid` file.   Changing the listen address to ipv4,  it would start.

@elsloo installed a couple of extra Perl modules which seemed to resolve the issue.   I'm working on setting up another clean server to test this out...

The Perl modules involved are:
   - `IO::Socket::IP`
   - `IO::Socket::SSL`
   - `IO::Socket::INET6`

**Comment by smalenfant** [comment]
We've been using `https://[::]:443?..` for a while without side effects with base install.

Here's my `IO` directory which I don't think we modify... Was `postinstall` re-run?

```
[ansible@cdn1cdcms0001 Socket]$ ls -l
total 236
-r-xr-xr-x 1 trafops trafops 38800 Jul 18 14:37 IP.pm
drwxr-xr-x 2 trafops trafops  4096 Jul 18 14:37 SSL
-r--r--r-- 1 trafops trafops 98839 Jul 15 08:23 SSL.pm
-r--r--r-- 1 trafops trafops 79951 Jul 14 08:48 SSL.pod
-r--r--r-- 1 trafops trafops 11017 Sep 29  2015 Timeout.pm
```

**Comment by dangogh** [comment]
yes -- postinstall was run.  Possibly another Perl module was updated in the process that caused this.   I'd like to get with you over slack to compare module versions and update this thread with any additional information.

**Comment by dangogh** [comment]
closing this until we see evidence of it not working on a cleaner setup.
