### ISSUE TITLE
TO: CR-Config not created with mixed Profiles

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#1622]
Due to a configuration issue, Snapshot CRConfig would not show any configuration/diff on the UI.

Way to reproduce :
- Copy your current CCR profile to CCR_X
- Change that new profile to a bogus domain_name parameter (add and remove old)
- Assign that new profile to an existing Traffic Router

Note: There was no DEBUG information at all in the logs.

**Comment by dg4prez** [comment]
Don't do that.
