### ISSUE TITLE
Error on creating ANY_MAP deliveryservice without a HOST regexp.

### ISSUE THREAD

**Issue by knutsel** [Comcast/traffic_control#1643]
`Traffic Ops fatal error occurred while processing your request. 
Error at line () 
empty domain label at /opt/traffic_ops/app/local/lib/perl5/x86_64-linux-thread-multi/Net/DNS/RR.pm line 409. in new Net::DNS::RR( name .cdn.example.com. type DNSKEY algorithm 5 fla ... ) at /opt/traffic_ops/app/local/lib/perl5/Net/DNS/SEC/Private.pm line 139.`

**Comment by dangogh** [comment]
no longer happens
