### ISSUE TITLE
portal.registration_email_from value is not being respected

### ISSUE THREAD

**Issue by mitchell852** [Comcast/traffic_control#167]
Registration emails are coming from a different "from" address than the one defined in /opt/traffic_ops/app/conf/cdn.conf

From TrafficOps.pm

```
my $registration_email_from = $config->{'portal'}{'registration_email_from'};
if ( defined($registration_email_from) ) {

	$self->plugin(
		mail => {
			from => $registration_email_from,
			type => 'text/html',
		}
	);

}
```

**Comment by mitchell852** [comment]
currently, registration emails are coming from - no-reply@flashgen.acs006.internap.com

**Comment by dewrich** [comment]
This ended up being a DNS and configuration issue, should now be mapped to our agreed upon domain
