### ISSUE TITLE
ToORTCheck and traffic_ops_ort.pl

### ISSUE THREAD

**Issue by hbeatty** [Comcast/traffic_control#1675]
Issue:
The ToORTCheck sometimes reports incorrectly due to traffic_ops_ort already being run on the cache servers.

Resolution:
- Move the functionality of the ToORTCheck into the traffic_ops_ort
  - This is not that big of a change since the ToORTCheck is running the traffic_ops_ort and capturing the output
- Have the traffic_ops_ort post results back to TO in the ORT column

Other enhancements in conjuction:
- UI: The ORT column would become a link to the results of the run
  - Store the results of the run in the DB that would be overwritten on the next run.
- UI: Create a new column in the "Server Checks" table for syncds and report those
  - Have this column as a link to the actual report that would be stored in the DB. Overwritten on the next run.
- Would want the "report" mode and "syncds" mode to not interfere with one another.
  - Perhaps allow these two to run simultaneously? Other suggestions welcome.
- The "report" mode would run every 4 hours on the cache server. Is it needed that often? 8? 12? 24?

**Comment by knutsel** [comment]
I agree with all of these proposed changes. 

I don't think we should allow the syncds and report modes to run at the same time (what are you reporting on if it is being changed at the same time?). Maybe something where a syncds reports also every X times it is called when it is done (regardless of if it did any updates)? We'd have to probably keep a counter in the DB for that, or just look at the timestamp of /tmp/ort/syncds.log, and if it was from yesterday, you report; that'll give you a report every 24 hours.

Implementation wise, I am not sure if we want to add columns to the servercheck table with the result text(s), or if we would have a separate table and link to that. @PSUdaemon waddaya think?

**Comment by hbeatty** [comment]
I like the counter for the report in the DB. That would allow it to be configurable.

**Comment by smalenfant** [comment]
What about putting this in InfluxDB instead and get rid of the to_extension table?

- Keep history based on all counters (Warning, Errors, Fatals)
- Keep history of the output in the InfluxDB
- Self clean with retention policy
- Probably easy to create a template based on checks/data available without changing Traffic Ops code base.
- Extendable to other servers than just Edge/Mid.
- Can post using InfluxDB directly or simply picked up from a log using Telegraf (which is already running on servers for some of us)

This might also scale better instead of posting to Traffic Ops. Line protocol is simple and efficient.

**Comment by knutsel** [comment]
I think we still need the to_extensions table... This would go in to the server_status table, and maybe you mean we get rid of that? Hmm.... Hank?

**Comment by hbeatty** [comment]
I would have to look at the code more closely to figure out whether we could get rid of either of those tables eventually. I can say that any To...Check currently written would have to be modified before either table could be removed. So maybe table (haha! get it?) that for now.

The rest of it I agree with and recommend moving in the direction Steve suggests.

**Comment by hbeatty** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;xWxt84UZ&#x2F;7-traffic-ops-ort-pl-enhancement"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> traffic_ops_ort.pl enhancement</a>
