### ISSUE TITLE
traffic_router/monitor not monitoring if cache is disabled

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#170]
There is a variable accessible in ATS which tells us if cache is enabled/disabled. Currently disabled caches are still used by Traffic Router. There is currently no notification that configuration is potentially wrong.

There should probably be an override to make sure traffic_router can use ATS with disabled cache as last resort.

These should also be taken into consideration :  
proxy.node.restarts.manager.start_time: 1401710734
proxy.node.restarts.proxy.start_time: 1401710735

Disabled :  
[ansible@xyz01 bin]# sudo /opt/trafficserver/bin/traffic_line -m proxy.node.restarts.proxy.cache_ready_time
proxy.node.restarts.proxy.cache_ready_time 0

Enabled :  
[ansible@xyz02 ~]$ sudo /opt/trafficserver/bin/traffic_line -m proxy.node.restarts.proxy.cache_ready_time
proxy.node.restarts.proxy.cache_ready_time 1432033870

From diags.log :  
[May 28 01:14:39.131] Server {0x2b93f1ffe080} WARNING: unable to open cache disk(s): Cache Disabled
[May 28 01:14:39.140] Server {0x2b93f1ffe080} NOTE: traffic server running

**Comment by mtorluemke** [comment]
Oh, I see now -- cache_ready_time is 0 if not enabled -- good.

**Comment by knutsel** [comment]
Is this a change tor TM or TS?

**Comment by elsloo** [comment]
@smalenfant: do we want to simply poll for this stat so we can store it in Traffic Stats or in memory in Traffic Monitor for other uses, or take action if the cache is disabled (read: not route traffic to it)? If the latter, we'll need to think about this a bit more, as although it's unlikely, some users could technically want to run ATS with the cache disabled, and we currently don't have the context in Traffic Monitor and Traffic Router to know whether the cache should or should not be enabled on a given cache.

Thoughts?

**Comment by smalenfant** [comment]
@elsloo 

1. Get the value available in memory for other uses (InfluxDB + Kapacitor or Traffic Ops Checks)
2. Add a Traffic Monitor conditional like availableBandwidthInKbps (Ex. health.threshold.cacheEnabled > 0) so you don't want this cache in the rotation (Don't hammer your origin for nothing!). 

Are the thresholds configurable for anything else in Traffic Monitor? How does that work?

**Comment by dangogh** [comment]
already merged
