### ISSUE TITLE
Allow hostnames in ilo_ip_address

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#171]
Some deployments are using DHCP/Hostnames instead of specifying ilo IP/Netmask/GW. We tried to re-use the ilo_ip_address field to put a hostname (example, idrac-ServiceTag.mgt.kabletown.net), but the IP verification would make it fail.

I believe iDrac/ILO needs to be configured before they can be used by Traffic Ops to provision a server. Is the netmask/gateway information useful? Could it be removed?

If that's OK, I'd like to make that change.

**Comment by mtorluemke** [comment]
@dangogh: maybe new column.

**Comment by nir-sopher** [comment]
Already Merged
