### ISSUE TITLE
Load of ssl_multicert.config fails

### ISSUE THREAD

**Issue by dg4prez** [Comcast/traffic_control#1735]
Unable to load ssl_multicert.config file in the lab environment.  This fails with both ORT and by entering the genfiles url in the browser.  Browser result:

> Traffic Ops fatal error occurred while processing your request. 
> Error at line 126 ( and $self->hook(around_action => sub { $_[2]->($_[1]) })) 
> Can't locate object method "get_cdn_domain" via package "UI::DeliveryService" at /opt/traffic_ops/app/local/lib/perl5/Mojolicious.pm line 126.

**Comment by dangogh** [comment]
for completeness,   route that caused the error was this:
`.../genfiles/view/edgecachehostname/ssl_multicert.config`
