### ISSUE TITLE
Graph link on Server page for servers that are not caches

### ISSUE THREAD

**Issue by dneuman64** [Comcast/traffic_control#1736]
On the servers page in TO there is a graph icon which leads to graphs for caches.  This icon is currently not present for other types of servers such as Traffic Routers, Traffic Monitors, Influxdb servers, etc.  We should create some scripted dashboards and update Traffic Ops so that all server types have graphs with at least grafana data.

**Comment by dg4prez** [comment]
https://issues.apache.org/jira/browse/TC-318
