### ISSUE TITLE
Transition support from cacheurl to cachekey ATS plugin

### ISSUE THREAD

**Issue by mtorluemke** [Comcast/traffic_control#1739]
From the ATS users list:

Hello ATS users,

We are removing cacheurl plugin in 7.0.0 release.

As it was already mentioned in its documentation in 6.2.0 release:
    https://docs.trafficserver.apache.org/en/6.2.x/admin-guide/plugins/cacheurl.en.html
this plugin was deprecated as of v6.2.0 and now we are removing it as of v7.0.0. 

It is replaced by a new Cache Key Manipulation Plugin:
    https://docs.trafficserver.apache.org/en/latest/admin-guide/plugins/cachekey.en.html

If you have not already replaced it please find some examples below:
    https://docs.trafficserver.apache.org/en/6.2.x/admin-guide/plugins/cacheurl.en.html#converting-to-admin-plugins-cachekey
    https://docs.trafficserver.apache.org/en/latest/admin-guide/plugins/cachekey.en.html

Please let me know if any problems or concerns!
Thank you,
—Gancho

**Comment by dg4prez** [comment]
This is on my to-do list.
