### ISSUE TITLE
Traffic Router requires at least one cache assigned to at least one DS for TLD zone generation

### ISSUE THREAD

**Issue by elsloo** [Comcast/traffic_control#1745]
In order for the CDN TLD's zone file to be generated, at least one cache must be assigned to one delivery service. This is due to the way the super domains are created; the current algorithm generates the super domains based on a loop through cache assignments. If no caches are assigned, the super domains list is empty, and the TLD zone is never created.

The impact is that people standing up new Traffic Control CDNs will have a non-functioning Traffic Router in terms of domain delegation and resolution due to the missing TLD.

**Comment by dangogh** [comment]
https://issues.apache.org/jira/browse/TC-305
