### ISSUE TITLE
For each deliveryservice, show the dsID in traffic ops and traffic portal

### ISSUE THREAD

**Issue by mitchell852** [Comcast/traffic_control#1750]
![image](https://cloud.githubusercontent.com/assets/251272/17978137/da819b68-6ab1-11e6-9ed5-673f825b25d7.png)

^^ Add a disabled form field for dsID to the delivery service detail page in TO

Also, add the ID to the deliveryservice table in TP as well as the ds details page.

![image](https://cloud.githubusercontent.com/assets/251272/17978257/4a8c4e6c-6ab2-11e6-83ea-d56ce1499727.png)

![image](https://cloud.githubusercontent.com/assets/251272/17978277/67796a0a-6ab2-11e6-905d-1c71fc357c1a.png)

**Comment by mtorluemke** [comment]
@mitchell852 this is a new column?

**Comment by mitchell852** [comment]
sorry, not a database column. just a column in a UI table...
