### ISSUE TITLE
Delivery service TTLs/SOA data are hard coded in CRConfig generation code

### ISSUE THREAD

**Issue by elsloo** [Comcast/traffic_control#178]
The TTLs and SOA timing data (retry, etc) that appear in the delivery service object in the CRConfig are currently hardcoded.  This means, for example, that there is no way to adjust the TTL or timing values in the SOA, or TTLs of things like NS records.  These should be configurable on a per-delivery-service basis, and if the values don't exist, the defaults from the Traffic Router's profile parameters should be used.  Only if the profile parameters are missing should we fall back to hardcoded values.

**Comment by limited** [comment]
https://issues.apache.org/jira/browse/TC-289
