### ISSUE TITLE
Add Traffic Monitor 2.0 down cache highlighting

### ISSUE THREAD

**Issue by robert-butts** [Comcast/traffic_control#1794]
GUI needs to highlight down cache rows in bright red or something.

**Comment by elsloo** [comment]
A detected problem should be something bright such as red, but an `ADMIN_DOWN` host should be a less severe color such as orange.

**Comment by robert-butts** [comment]
@elsloo Done. https://github.com/robert-butts/traffic_control/commit/64812b417e7f471e78678ff0706e8004b9afa834
