### ISSUE TITLE
Upload server csv example file is missing https_port 

### ISSUE THREAD

**Issue by mitchell852** [Comcast/traffic_control#1799]
which results in an error like this when trying to use good.csv

![image](https://cloud.githubusercontent.com/assets/251272/18215196/46e45e7e-710d-11e6-80a9-2a8cf7f3429a.png)

plus the code can't account for the new field even if it was included in the source csv.

**Comment by elsloo** [comment]
While you're in there, can we maybe update the CSS behind that white box so that it matches the rest of the UI? If not for this regression, maybe for master?
