### ISSUE TITLE
Add "wrap_count" to server scripted dashboard

### ISSUE THREAD

**Issue by dneuman64** [Comcast/traffic_control#1800]
- Update Influxdb_tools/create_ts_databases to include CQ for wrap_count (ats.proxy.process.cache.volume_x.wrap_count)

- Upate Influxdb_tools/sync_ts_databases to sync wrap_count data

- Update scripted dashboard to include scripted data. (It is a counter)
https://grafana-url/dashboard/script/traffic_ops_server.js?which=<cache>

**Comment by smalenfant** [comment]
Will Traffic Stats pick this field up and put in influxDB? Been working on getting this information over here as well, but then the wrap_count resets after traffic server is restarted ( although that's not been consistent ).

**Comment by dneuman64** [comment]
This issue has been moved to Jira here:  https://issues.apache.org/jira/browse/TC-2
