### ISSUE TITLE
TO: Dockerfile references dead cpan repo

### ISSUE THREAD

**Issue by dangogh** [Comcast/traffic_control#1802]
cpan.yimg.com no longer exists.  Remove from dockerfile

**Comment by dangogh** [comment]
Don't know why merging #1801 didn't close this, but yes -- it's done..  Thanks, @JJ --  closing..

**Comment by JJ** [comment]
:+1:

Pity... It was one I could actually do :-)

**Comment by dangogh** [comment]
still lots of others there :-)  Join the google group and ask questions if you need any pointers:

https://groups.google.com/forum/#!forum/traffic_control-discuss
