### ISSUE TITLE
traffic_ops.ort.pl fails with syntax error

### ISSUE THREAD

**Issue by jrushford** [Comcast/traffic_control#1806]
traffic_ops_ort.pl fails with the folowing error.

[root@cdn1cdedge0010 ort]# /opt/ort/traffic_ops_ort.pl badass debug https://cdn1cdcms0001.coxlab.net chs:w@term@rk -dispersion=0
syntax error at /opt/ort/traffic_ops_ort.pl line 2510, near "else"
Missing right curly or square bracket at /opt/ort/traffic_ops_ort.pl line 2587, at end of line
Execution of /opt/ort/traffic_ops_ort.pl aborted due to compilation errors.

**Comment by dneuman64** [comment]
this was fixed by https://github.com/Comcast/traffic_control/commit/2fd26e06fcd84f100b163edc2cacdfedc9ade7f2
