### ISSUE TITLE
Modify ConfigFiles.pm for cachegroup-based MSO ordering

### ISSUE THREAD

**Issue by dg4prez** [Comcast/traffic_control#1814]
Currently we have no way to set the primary/secondary servers for multisite configurations by anything other than a static rank value.  I propose the following change in logic during parent configuration at the mid:

1) Check primary/secondary parent cachegroups for mid.
2) If any of the assigned origins have cachegroups matching the primary cachegroup (if any), write these entries first, using rank as a secondary sort factor if more than one origin is in this primary cachegroup.
3) Repeat for mid's secondary cachegroup (if any).
4) Process remaining by rank (if any).
5) Process remaining.

By creating origin server cachegroups for each region and selecting these as the primary and secondary parent cachegroup for each mid's cachegroup, we could then have cachegroup-specific primary and secondary preferences.  This will allow the system to automatically generate a parent config for each mid that uses the origin sort order most optimal for its location in MSO primary/secondary configurations.  On the delivery service side, we need only create a delivery service with a primary/secondary MSO config and make certain that the origin servers, if needed, are put in the appropriate origin cachegroups.  The DB and UI requirements are already in place for such a modification.

**Comment by knutsel** [comment]
So digs us deeper in to the current, very confusing paradigm where the origins are in a cg and the origin cg is a parent of the mid cg... Should we consider going back to the drawing board and try to come up with something else?

**Comment by dg4prez** [comment]
I think that this is a pretty simple change to make, since it can be done with the one file and section of code.  This functionality is needed ASAP.  In the longer term, I agree - MSO should get a ground-up redesign.

**Comment by smalenfant** [comment]
Which exact feature is this about? MSO algorithm with Primary/Backup selection? I believe I tested that in the past, worked for the MSO config, but not for the default `dest_domain=*.` Do you have an example configuration used and the results?

**Comment by dg4prez** [comment]
This is to provide primary/backup selection that is cachegroup sensitive.  The idea is to assign origin servers to location-based cachegroups, and set these cachegroups as the primary or secondary cachegroups for the mid cachegroups.

In cases where these exist, we would evaluate by primary/secondary cachegroup for each mid's parent config, and then rank.  This would allow us to use either or both.  Rank works at the delivery service level, where cachegroup would work per-mid for location specific primary/secondary/tertiary configuration.

This is needed for cases where you want one group of mids to use a specific origin over another, more distant origin.

At this point we're only getting one origin.  From the looks of things, that's because the parent_data sub gives different data for mid servers.  Not sure how to resolve that yet, any help would be appreciated.

**Comment by dneuman64** [comment]
I think this should have been closed with #1822.  If not, please re-open...
