### ISSUE TITLE
Stats: socket: too many open files after long run time

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#1825]
TCP connection table builds up with ESTABLISHED connections over time, leading to traffic_stats to stop. Ours took about 2 months to go over 55k.

Connections should be closed if not re-used.
I suggest restarting traffic_stats weekly until fixed.

Version: `traffic_stats-1.6.0-3500.9d1ef9d1.x86_64`

```
[10361868.083500] TCP: too many orphaned sockets
[10361868.083501] TCP: too many orphaned sockets
[10361868.083502] TCP: too many orphaned sockets
[10361868.083503] TCP: too many orphaned sockets
[10361874.139353] net_ratelimit: 11219 callbacks suppressed
```

**Comment by robert-butts** [comment]
FWIW we're seeing a similar issue with Traffic Monitor 2.0 (https://github.com/Comcast/traffic_control/tree/master/traffic_monitor/experimental). It has trouble getting new sockets after 1–7 days.

Seems likely they're the same issue. I.e. Go doesn't properly close connections over time. I'm currently investigating TM2, I'll post findings here as well.

The solution may require disabling keepalives altogether. Hopefully not; that would probably significantly reduce capacity.

In TM2, it's odd connections aren't properly reused. We have far fewer caches than sockets, the connection count should never exceed the number of caches by much. 

It would also be odd if they weren't being garbage-collected, but not impossible. Go's GC is stop-the-world for 10ms, then concurrent if it doesn't finish (See https://docs.google.com/document/d/16Y4IsnNRCN43Mx0NZc5YXZLovrHvvLhK_h0KN8woTO4/edit). I'd be surprised if the number of caches/connections we have took more than 10ms to free. But if that is the problem, it may be fixable with https://golang.org/pkg/runtime/#GC, https://golang.org/pkg/runtime/debug/#SetGCPercent, https://golang.org/pkg/runtime/#hdr-Environment_Variables
