### ISSUE TITLE
Add Traffic Monitor 2.0 memory and goroutine stats endpoint

### ISSUE THREAD

**Issue by robert-butts** [Comcast/traffic_control#1849]
These will not only give us an at-a-glance view, but also let us poll them from Telegraf and Grafana. This will let us see when memory or goroutine leaks exist.

This should probably be put in an existing stats endpoint.

**Comment by dneuman64** [comment]
I would think of other things that are interesting and include those as well...maybe things like http requests, polling counters, etc.
