### ISSUE TITLE
traffic_ops_ort.pl exposes password. 

### ISSUE THREAD

**Issue by petrocc** [Comcast/traffic_control#188]
When one runs traffic_ops_ort.pl you must provide a username and password for the TO instance on the commandline.

This exposes the password during the ort process via the process table and (on many version of Linux) will store that command in the .bash_history file. 

traffic_ops_ort.pl should be modified such that when a username is provided without a password one is requested.

**Comment by dneuman64** [comment]
moved to https://issues.apache.org/jira/browse/TC-293 closing
