### ISSUE TITLE
Add RESTful API: get servers by profile

### ISSUE THREAD

**Issue by jifyang** [Comcast/traffic_control#1902]
The APIs document is at https://docs.google.com/document/d/13GjIizusc7iUZq7TuVrsp8JZ2eEx52xUtoX9uRNzFgc/edit?usp=sharing

3.10.5  Get servers by profile

**Comment by mitchell852** [comment]
@jifyang - make sure you assign this issue to yourself if you plan to / did the work

**Comment by jifyang** [comment]
@mitchell852 - I can't find the way to assign this issue to myself. Could you tell me how to do this? Thanks.
