### ISSUE TITLE
add RESTful for parameters CRUD

### ISSUE THREAD

**Issue by yorma** [Comcast/traffic_control#1915]
document is at https://docs.google.com/document/d/13GjIizusc7iUZq7TuVrsp8JZ2eEx52xUtoX9uRNzFgc/edit?pref=2&pli=1#heading=h.mqca5ywtusd3

3.5.1. POST /api/1.2/parameters   -- create parameters
3.5.2. PUT /api/1.2/parameters/{:id}  --- edit parameter
3.5.3. DELETE /api/1.2/parameters/{:id}  --- delete parameter
3.5.7. POST /api/1.2/paramters/validate  --- valid if the parameter exists
3.5.8. GET /api/1.2/parameters/{:id} -- get parameter from id

**Comment by mitchell852** [comment]
parameter crud has already been implemented.
