### ISSUE TITLE
RHEL/CentOS 6.6+ cacerts certificate installation error

### ISSUE THREAD

**Issue by elsloo** [Comcast/traffic_control#192]
The following error occurs when upgrading (installing?) traffic_router on RHEL/CentOS 6.6.  This could also occur on later versions.

```
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
 Updating   : traffic_router-1.1.2-832f1e6fa.el6.x86_64                                                                                                              1/2
Non-fatal POSTIN scriptlet failure in rpm package traffic_router-1.1.2-832f1e6fa.el6.x86_64
/opt/tomcat installed
Installing certificate COMODOHigh-AssuranceSecureServerCA.crt..
Certificate was added to keystore
keytool error: java.io.FileNotFoundException: /etc/alternatives/../jre/lib/security/cacerts (No such file or directory)
warning: %post(traffic_router-1.1.2-832f1e6fa.el6.x86_64) scriptlet failed, exit status 1
```

**Comment by elsloo** [comment]
This could also be partially due to the fact that our newer CentOS 6.6 Traffic Routers are running Java 7; our older 6.5 instances are running Java 7 (Chicago) and Java 6 (Denver).

**Comment by elsloo** [comment]
This is due to lines 40 and 44 in postinstall.sh being unable to properly locate the cacerts file with this OS/JVM combo.

**Comment by limited** [comment]
Cheap workaround just to get the RPM installed:

<jre_path> = readlink /etc/alternatives/jre
ln -s <jre_path> ./jre
