### ISSUE TITLE
Traffic Ops escapes forward slashes in CR Config

### ISSUE THREAD

**Issue by trevorackerman** [Comcast/traffic_control#1986]
It puts a backslash before the forward slash separating the host and netmask for ip6 addresses
And it also does this for forward slashes in URL's used by traffic router

**Comment by mitchell852** [comment]
I can't reproduce this. In both the master branch and the psql-rebase branch, I performed a snapshot which generated the CRConfig.json file and searched for '\/' and found nothing and well as searched for '::' to look at ipv6 addresses which looked fine. closing.
