### ISSUE TITLE
ERROR https://ops.cdn.reyzar.net/api/1.1/deliveryservices/hostname/edge.baidu.cdn.reyzar.net/sslkeys.json returned HTTP 400!

### ISSUE THREAD

**Issue by weijian2014** [Comcast/traffic_control#1997]
I add the HTTPS delivery services to Ops and "Queue Updates". The ATS(EDGE) execute /opt/ort/traffic_ops_ort.pl by crontab. But the "remap.config" dost not the HTTPS record(The HTTP record is ok before add the HTTPS delivery services)
I execute the traffic_ops_ort.pl script that show result below:
`ERROR Lines for /opt/trafficserver/etc/trafficserver/ssl_multicert.config from Traffic Ops do not match file on disk.
ERROR Config file ssl_multicert.config line only in TrOps:	ssl_cert_name=edge_baidu_cdn_reyzar_net_cert.cer ssl_key_name=edge.baidu.cdn.reyzar.net.key
ERROR Config file ssl_multicert.config line only in TrOps:	ssl_cert_name=edge_taobao_cdn_reyzar_net_cert.cer ssl_key_name=edge.taobao.cdn.reyzar.net.key
ERROR Creating backup of file on disk for ssl_multicert.config.
ERROR Creating backup of file in TrOps for ssl_multicert.config.
ERROR https://ops.cdn.reyzar.net/api/1.1/deliveryservices/hostname/edge.baidu.cdn.reyzar.net/sslkeys.json returned HTTP 400!
ERROR result for https://ops.cdn.reyzar.net/api/1.1/deliveryservices/hostname/edge.baidu.cdn.reyzar.net/sslkeys.json is: ...{"alerts":[{"level":"error","text":"Error  - A record for ssl key -latest could not be found.  Response was: No RIAK servers are set to ONLINE in the database.  Please verify RIAK servers are online and reachable from Traffic Ops."}]}...`

**Comment by weijian2014** [comment]
Problem has been solved! My "Regular expressions for this delivery service" for HTTPS delivery services was wrong.
before:   .*baidu.*
after:    .*\.baidu\..*
Now, the remap.config have the HTTPS record and I will test HTTPS origin server for my Traffic Control!

**Comment by mtorluemke** [comment]
Good news!
