### ISSUE TITLE
The url_sig_xxx.config not found

### ISSUE THREAD

**Issue by weijian2014** [Comcast/traffic_control#2005]
The edge cache server disable when configuration "Signed URLs" type "yes" for HTTPS delivery services.  SSL keys was generated and "Queue Cache Updates" was submitted.
The url_sig_xxx.config not found as below:
traffic_ops_ort.pl
![traffic_ops_ort pl](https://cloud.githubusercontent.com/assets/7225360/19305887/a56301fa-90a5-11e6-8bca-740c35c71b24.png)

diags.log
![diags log](https://cloud.githubusercontent.com/assets/7225360/19305895/b51417a6-90a5-11e6-8664-345dab20b0fa.png)

traffic.out
![traffic out](https://cloud.githubusercontent.com/assets/7225360/19305910/c5bb6442-90a5-11e6-9e9f-7849edf79963.png)

"find / -name url_sig_004.config" not found for edge cache host and Ops host.

**Comment by smalenfant** [comment]
Sorry about closing/re-opening... Was reading and hit by mistake.

**Comment by dg4prez** [comment]
This happens when a parameter is not created for the file.
