### ISSUE TITLE
TO:   Net::Riak cpan module fails to install

### ISSUE THREAD

**Issue by dangogh** [Comcast/traffic_control#2024]
Net::Riak depends on Google::ProtocolBuffers.   That module has been updated in CPAN and now requires perl 5.12.    On Centos 6.x,  perl 5.10 is the latest available.

I think specifying Google::ProtocolBuffers 0.11 (previous version) should solve this,  but need to test that out..

**Comment by mitchell852** [comment]
fixed. see referenced PRs.
