### ISSUE TITLE
Traffic-monitor invalid JSON

### ISSUE THREAD

**Issue by behzad-kh** [Comcast/traffic_control#2034]
Hello
An error occurred while installing traffic monitor. It seems that something is missing in the traffic-ops, but I don't know what!!!!

[root@Traffic_Monitor ~]# /opt/traffic_monitor/bin/traffic_monitor_config.pl https://TRAFFIC_OPS_IPADDRESS_OR_FQDN admin:PASSWORD prompt
DEBUG: Found hostname: Traffic_monitor
DEBUG: traffic_ops selected: https://TRAFFIC_OPS_IPADDRESS_OR_FQDN
DEBUG: traffic_ops login: admin:PASSWORD
DEBUG: Config write mode: prompt
**FATAL: https://TRAFFIC_OPS_IPADDRESS_OR_FQDN/ort/Traffic_monitor/ort1 did not return valid JSON!**

any idea?

**Comment by mitchell852** [comment]
If this error is still occuring please move it to the open source jira - https://issues.apache.org/jira/browse/TC
