### ISSUE TITLE
Cannot specify a delivery server on port other than 80

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#209]
If input my origin server with http://mserver.mydomain.com:8081, the GUI throws an error about some RFC not compliant.

Having a port on the origin server should perfectly valid.
I modified the database manually and added the :8081 at then. The configured made it through but didn't seem like the parent liked it at all.

2 things  
- GUI doesn't allow specifying the port
- ATS in forward mode tried to forward the request to origin on port 80 (possibly?)

**Comment by knutsel** [comment]
How is that CLA coming along? Looks like something you could tackle.

**Comment by smalenfant** [comment]
It's all ready to go.. Just waiting on the approval.

**Comment by smalenfant** [comment]
Little update. 

- The WEB UI doesn't let the change happen. DB can be updated manually (fix pending)
- When using Query String Handling == 2 (drop at edge), the regex_remap drops the port 8081 from the origin URL, thus forwarding the wrong information to parent (without port).

So, got it working with QSH == 0

drop_qstring.config 

```
/([^?]+) $s://$t/$1
```

**Comment by knutsel** [comment]
Will fix just the UI part of not being able to add a port to the base url. Opened #259 to track the QSH bug, need to come up with a new regex for that.
