### ISSUE TITLE
Traffic Monitor Web UI using lots of CPU in Chrome

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#210]
Other than killing my battery, works fine. But looks like it's wasting lots of CPU cycle when standing on the Traffic Monitor page.

**Comment by trevorackerman** [comment]
Currently seeing less than 10% cpu utilization in Chrome Version 47.0.2526.106 (64-bit) on my MacBook Pro

**Comment by elsloo** [comment]
Resolved via the above commit (and probably others). Please reopen if you experience similar performance with >= 1.4.x.
