### ISSUE TITLE
When parents are down, configs don't get applied

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#217]
We have a cluster of 6 Mid Cache. We are in pre-deployment and we brought Mid 3 down for maintenance (missing 2 disks in each). Now, the Edge won't update even if I put those 3 Mids that are down in "OFFLINE" state. 

I haven't looked at the logic yet, but if the Mids aren't updated, the config won't be pushed to the Edge.

Work around is to de-queue the updates on the Mids.

**Comment by mtorluemke** [comment]
I think this was fixed on 5/5/15 -- git blame of lib/UI/Server.pm shows:

8a94a2dd (Dewayne Richardson 2015-05-05 15:13:08 -0600 837)                             if ( $prow->upd_pending == 1 && $prow->status->name ne "OFFLINE" ) {

Which looks to have made it into 1.1.2 -- were you running 1.1.2 when you saw this?

**Comment by smalenfant** [comment]
We are still on 1.1.1. Possible this fixes the issue.
