### ISSUE TITLE
Traffic Ops ORT didn't pick up changes for LogFormat

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#231]
I made a change to Default LogFormat from #230. But the changes didn't apply using a normal syncds. All hosts had to be updated using the badass mode.

```
Wed Jun 17 01:17:38 UTC 2015
Version of this script: 0.47a
WARN Sleeping for 5 seconds: .....
ERROR Traffic Ops is signaling that an update is waiting to be applied.
WARN Sleeping for 15 seconds: ...............
ERROR Deleting directories older than 1433899058
ERROR Received error code 404 for https://trafficops.domain.net/Trafficserver-Snapshots/test_cdn/regex_revalidate.config from Traffic Ops!
ERROR Traffic Ops is signaling that an update is ready to be applied, but none was found! Clearing update state in Traffic Ops anyway.
```

**Comment by smalenfant** [comment]
@mtorluemke Since this parameter is in records.config, is there a way to still trigger to apply in SYNCDS mode ?

**Comment by mtorluemke** [comment]
Today, there isn't. There is an open issue to change the signaling to ORT of which config files are reloadable, and which ones require restart. Historically, many of the config files required a restart, and we've been working towards getting them all reloadable, but we aren't there yet. This migration results in different ATS versions having different functionality, and having to build the parameters in Traffic Ops appropriately, and keeping a close eye on the ORT version to make sure they are in sync.

**Comment by mtorluemke** [comment]
Did you manually put the file in place on a single cache, and run traffic_line -x, and where the changes applied? That is the key test in moving this config file from restart to reload.

**Comment by smalenfant** [comment]
I modified a file directly on a cache and issues traffic_line -x.
