### ISSUE TITLE
Missing CDN_name parameter causes API call to break

### ISSUE THREAD

**Issue by elsloo** [Comcast/traffic_control#246]
When the CDN_name parameter is missing from any server, it causes the routing API (/api/1.1/deliveryservices/:ds_id/routing.json) to break.

[2015-06-19 15:42:04,317] [ERROR] Can't call method "parameter" on an undefined value at /opt/traffic_ops/app/script/../lib/MojoPlugins/Health.pm line 124.

..tracing this code led to the missing parameters causing this.  Adding a dummy CDN_name parameter to profiles without one resolved the issue as a temporary workaround.

We should probably just check to see if $param and $param->parameter are defined on line 124, and continue to the next iteration if not.

**Comment by jheitz200** [comment]
Closing issue.  The CDN_name parameter has been removed from the code base.
