### ISSUE TITLE
Drop querystring doesn't work when there is a port specified in the org server base url. 

### ISSUE THREAD

**Issue by knutsel** [Comcast/traffic_control#259]

**Comment by mtorluemke** [comment]
You landed this, right?

**Comment by hbeatty** [comment]
@mtorluemke by, "You landed this, right?" Are you asking me to review what Steve did?

**Comment by smalenfant** [comment]
Yeah, it was. Although we know this doens't work without header_rewite in the way. How are we going to bring this up with Traffic Server team?

**Comment by dangogh** [comment]
already merged
