### ISSUE TITLE
Extra IPv6 line in ip_allow.config on mids

### ISSUE THREAD

**Issue by knutsel** [Comcast/traffic_control#274]
ERROR Config file ip_allow.config line only in TrOps:	src_ip=0:0:0:0:0:0:0:0-0:0:0:FFFF:FFFF:FFFF:FFFF:FFFF action=ip_allow method=ALL

Not sure where it comes from; started in 1.1.3

**Comment by smalenfant** [comment]
I don't have this line present in my Mid Caches in 1.1.3.

**Comment by mtorluemke** [comment]
Confirmed; we don't see either.
