### ISSUE TITLE
DNS DS, allow CNAME instead bypass IPv4/IPv6

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#280]
When I setup a DNS Delivery Service, the bypass options are "Bypass IP" and Bypass "IPv6". Is there a way to use a single CNAME instead?

**Comment by elsloo** [comment]
Traffic Router supports the use of a CNAME as a bypass destination, but it is not currently configurable within Traffic Ops.  If we add "cnameAlias" as a key under the bypassDestination->DNS object in the CRConfig, Traffic Router should send the CNAME with the value associated with "cnameAlias."

**Comment by elsloo** [comment]
While I was reading issue #341, it dawned on me that we will be unable to reach the cnameAlias code if no "ip" is in the DNS bypassDestination object due to the way we are attempting to load data from the JSON.  This bug needs to be corrected before this feature will work.
