### ISSUE TITLE
FQDN Check should not do ping, but check DNS records

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#286]
There is 10G and 10G6 that already does verification for IPv4 and IPv6. Unless FQDN was intended to do something else, seems like doing a ping test again would be pointless and would only test IPv4 hostname.

I can see the following instead 
- 10G and 10G6 ping checks along with an FQDN check that verifies both A and AAAA records matching Traffic Ops server configuration or
- 10G doing FQDN + ICMP on IPV4 and same for 10G6 (although, would be hard to diagnose if ICMP or DNS Failed)

We can tackle this simple tasks. Let's just know which one would be best.

**Comment by hbeatty** [comment]
This can be closed.
related commits:
11c18e8fc1466de06f107104dd97bf0623e8609d
65a6e27b2c0f50580837789a88fae376c34a1202

**Comment by elsloo** [comment]
Closing due to Hank's comment above.
