### ISSUE TITLE
ip_allow.config needs Traffic Monitor IPs

### ISSUE THREAD

**Issue by mtorluemke** [Comcast/traffic_control#290]

**Comment by dneuman64** [comment]
Traffic Monitors should be in the config file when a mid is in a reported OR online state

**Comment by jheitz200** [comment]
This issue has been tested and we do not see any issues.

I modified the IP on two Traffic Monitors one with an`online` status and one with a `reported` status.  I then validated the IP showed up in the ip_allow.config.
