### ISSUE TITLE
Numbers of edges/caches assigned in Delivery Services tab. 

### ISSUE THREAD

**Issue by petrocc** [Comcast/traffic_control#307]
It would be nice to see the number of edges assigned that a delivery service is attached to, as well as the total number eligible.  Maybe re-use the "Active" column and have the counts of active servers in green and the inactive in red?

**Comment by knutsel** [comment]
the number of caches assigned is already there, I thought? 

what would the total number eligible be? the total number of caches in that CDN?

**Comment by petrocc** [comment]
I'm talking about in the <fqdn>/delivery_services where you can look at 
all the DSs at one time

That way your ops team could quickly scan that column for inactive 
services as well as services that might need re-balancing.

And yes, the total number eligible would be the total number for the CDN.
