### ISSUE TITLE
Add display_name column to deliveryservice table

### ISSUE THREAD

**Issue by mitchell852** [Comcast/traffic_control#317]
type = varchar(48)
null = no

initially seed the column with the value from xml_id

make sure to add this new field to the TO delivery service form.

mare sure to update the payload of the following apis as well:

/api/1.1/deliveryservices/:id
/api/1.1/deliveryservices

**Comment by mitchell852** [comment]
i see the column as

| Field                  | Type          | Null | Key | Default           | Extra                       |
| display_name    | varchar(1024) | YES  |     | NULL              |                             |

can it be changed to:

varchar(48) <-- the traffic portal handles long values but people should keep it short to avoid to much truncation
null = no (the traffic portal depends on a display name now)

**Comment by mitchell852** [comment]
and actuallly, while you're at it, i would recommend increasing the long_desc* fields to varchar(1024)

**Comment by knutsel** [comment]
@dangogh - can you take a look??

**Comment by mtorluemke** [comment]
@mitchell852: okay to close?

**Comment by mitchell852** [comment]
yep, looks good to me
