### ISSUE TITLE
uninitialized value in InstallUtils.pm on adding traffic ops username

### ISSUE THREAD

**Issue by dangogh** [Comcast/traffic_control#346]
Administration username for Traffic Ops:  admin
Use of uninitialized value $defaultValue in string at /opt/traffic_ops/install/lib/InstallUtils.pm line 59, <STDIN> line 2.

**Comment by mtorluemke** [comment]
@dangogh @daniel_kirkwood

**Comment by dangogh** [comment]
I no longer see this warning.
