### ISSUE TITLE
1.1.4 install does not re-apply configs on an upgrade

### ISSUE THREAD

**Issue by lwickline** [Comcast/traffic_control#347]
after doing a yum upgrade traffic_ops I had to restore my cdn.config from backup.

**Comment by knutsel** [comment]
@daniel_kirkwood

**Comment by dangogh** [comment]
I just installed 1.1.3,  made a minor change to cdn.conf then yum upgrade traffic_ops to upgrade to 1.1.4.    I see cdn.conf retained as it was and a new cdn.conf.rpmnew created in the same directory -- this is what I would expect.

Can you provide more details?

**Comment by mtorluemke** [comment]
Spoke to @lwickline -- we are going to close for now, and reopen later if it happens again.
