### ISSUE TITLE
traffic_ops 1.1.4 postinstall uninitialized value error

### ISSUE THREAD

**Issue by lwickline** [Comcast/traffic_control#350]
Use of uninitialized value $name in hash element at /opt/traffic_ops/app/local/lib/perl5/Mojolicious/Renderer.pm line 196.

happens with post install form traffic_ops 1.1.4 build 2040

**Comment by knutsel** [comment]
@daniel_kirkwood: is this fixed already?

**Comment by dangogh** [comment]
ahh..   yes -- it was pull request #380 -- add_helper was being called with no helper to add..
