### ISSUE TITLE
Mid Header Rewrite needs to be added to remap.config

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#363]
Due to a mis-behaving origin, I want to override the Cache-Control (there isn't any in my case) using "Mid Header Rewrite". The delivery service feature does write the proper file to disk, but there is no remap rule set (basically doesn't do anything).

The following map needs to be added when used: 

`map http://originfqdn http://originfqdn @plugin=header_rewrite.so @pparam=hdr_rw_mid_<xml_id>.config`

**Comment by smalenfant** [comment]
Problem solved. My MID profiles didn't have the location for remap.config, the code didn't trigger the generation. Not exactly sure how we can make sure that parameter is present...

**Comment by knutsel** [comment]
Still think we want to keep this open, I think TO should do better than this.

**Comment by smalenfant** [comment]
https://issues.apache.org/jira/browse/TC-264
