### ISSUE TITLE
No more logs in /var/log/traffic_ops/traffic_ops.log

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#364]
On the systems I upgraded to 1.1.3, seems like there is no more logging being sent to /var/log/traffic_ops_traffic.log.

Anybody else seeing the same problem?

**Comment by elsloo** [comment]
No; we're running traffic_ops-1.1.3-2001 from the website and have current timestamps in that log.  I would verify permissions on the directory structure to ensure that the trafops user can write to the file(s) and can access the log directory.  Also try taking a look at files opened by the trafops user via lsof or similar.

**Comment by knutsel** [comment]
did you look in /var/log/traffic_ops/ ?

**Comment by knutsel** [comment]
oh, doh. that's what you are saying... i remember we moved it, but too /var/log/traffic_ops/, i thought.

**Comment by smalenfant** [comment]
The log has been there before the 1.1.3 update. It seems like this is still
the location but nothing gets written to it anymore

**Comment by smalenfant** [comment]
Here's what I've done just now.. Nothing gets written to it.

# mv traffic_ops.log ~
#service traffic_ops restart

# ls -l /var/log/traffic_ops/traffic_ops.log

-rw-r--r-- 1 root root 0 Jul 31 15:58 /var/log/traffic_ops/traffic_ops.log


[root@cdn1cdcms01 traffic_ops]# rpm -qa | grep traf

traffic_ops-1.1.3-2001.x86_64

**Comment by elsloo** [comment]
Did you check whether the file was open via lsof?  I just removed both access.log and traffic_ops.log and they were recreated with the ownership of root:root, which matches what you saw.  The access.log file is being written to, however, I don't have any messages in traffic_ops.log.  That being said, this may be normal, as we have been working to reduce the cruft that appears in the application log.  If that's the case, try increasing the logging from ERROR to DEBUG in /opt/traffic_ops/app/conf/production/log4perl.conf, then restart traffic_ops.  You should then see debug output in traffic_ops.log.

**Comment by smalenfant** [comment]
Jeff, I'm not getting DEBUG messages. Thanks!

**Comment by elsloo** [comment]
We need a few things before we can proceed:
1) Run an lsof and grep for "/var/log/traffic_ops"
2) Run an lsof and grep for log4perl.conf
3) The contents of the log4perl.conf file found in the previous step

Based on that we'll have a better idea where to go next.

**Comment by smalenfant** [comment]
I'm sorry... That should have read "I'm getting debug messages".

**Comment by elsloo** [comment]
Phew! Looks like this is a non-issue and our cleanup was actually making things more quiet. I'm going to close this issue for the time being, but please let us know if we need to reopen it.

**Comment by smalenfant** [comment]
We could probably place a "traffic Ops {version} is starting" is the log.
Just so nobody complains the logs aren't working :)

**Comment by elsloo** [comment]
Fair enough, that's a good point.  I'm going to reopen this and tag it as a new feature request to ensure it gets done.
