### ISSUE TITLE
Add packaging scripts for traffic_stats

### ISSUE THREAD

**Issue by jifyang** [Comcast/traffic_control#378]
Currently there is no packaging scripts for traffic_stats.

**Comment by dneuman64** [comment]
Hello, 
Packing scripts for an RPM build are included with traffic_stats. Please see here:  https://github.com/Comcast/traffic_control/tree/master/traffic_stats

thanks,
Dave

**Comment by jifyang** [comment]
Hello Dave,

Currently under the directory traffic_stats, there is only the file “traffic_stats.spec”. It’s better to have a packing script to do the things such as tar the source code to *.tar.gz, setup VERSION/RELEASE etc. So the user can get the rpm package by running only one command.

Thanks,
Jifeng
