### ISSUE TITLE
"disallowed" doesn't "disallow" access.

### ISSUE THREAD

**Issue by petrocc** [Comcast/traffic_control#387]
Setting a user to "disallowed" should prevent them from logging in at all, including on any service that uses the API. 

Currently this is not the case.

**Comment by mitchell852** [comment]
as petro mentioned, setting a user to "disallowed" may prevent them from doing anything but doesn't prevent them from logging in.

in addition, it actually results in this api returning ALL delivery services.

/api/1.1/deliveryservices.json

so a "disallowed" user can see every property of every delivery service.

**Comment by mitchell852** [comment]
looks good from an api perspective:

curl -v -H "Accept: application/json" -v -X POST --data '{ "u":"disallowed_user", "p":"disallowed_user_password" }' http://localhost:3000/api/1.x/user/login

returns 401 unauthorized.
