### ISSUE TITLE
Sanity check to make sure SSL isn't set up on DNS services. 

### ISSUE THREAD

**Issue by petrocc** [Comcast/traffic_control#427]
According to conversations DNS delivery services don't work with SSL. It might be useful/wise to have a check that keeps DNS services from enabling SSL or setting up key storage for them.

**Comment by mtorluemke** [comment]
Currently, it's HTTP delivery services that we don't support.

**Comment by petrocc** [comment]
I know that now. Doesn't change the idea, just the implementation. 

s/DNS/HTTP/g

**Comment by dg4prez** [comment]
We now support ssl for http delivery services.
