### ISSUE TITLE
Trouble with setting up traffic router

### ISSUE THREAD

**Issue by kianooshm** [Comcast/traffic_control#432]
Hi there,

Not much info documented as to setting up Traffic Router: [here](http://traffic-control-cdn.net/docs/latest/admin/traffic_ops_using.html#ccr-profile-or-traffic-router-profile) and [here](http://traffic-control-cdn.net/docs/latest/admin/traffic_router.html).

The doc says, e.g., parameter `location/geolocation.properties` must be set to "Location to find the log4j.properties file for Traffic Router" which is BTW a wrong copy paste of the line above and probably wasmeant to say "Location to find the geolocation.properties file for Traffic Router." which gets me to the question of where that file is? (or how can it be produced? by Traffic Ops?)

Same question for "the location (URL) to retrieve the coverage zone map file in JSON format from", and the same map in XML format.

Moreover, there are few mysterious options in `/opt/traffic_router/conf/cache.properties`
* `cache.geolocation.database`: I manually put the file in `/opt/traffic_router/db/GeoLite2-City.mmdb` and got this parameter to point to it. It would be much nicer if, just like Traffic Monitor that has a script to pull the data it needs, Traffic Router does that too.
* `cache.health.json`: where to get / how to produce the health.json file?
* `cache.config.json`: this is probably the CRConfig.json snapshot create by Traffic Ops, right?
* `cache.czmap.database`: I got it to point to this coverage zone file: (created as per the sample [here](http://traffic-control-cdn.net/docs/latest/admin/traffic_ops_using.html#the-coverage-zone-file-and-asn-table))
```
{
    "coverageZones": {
        "MyCacheGroup": {
            "network": [
                "0.0.0.0\/0"
            ]
        }
    }
}
```
but i'm getting his exception which means that's not the file it wants:
```
WARN  2015-08-15T16:33:28.974 [main] com.comcast.cdn.traffic_control.traffic_router.core.monitor.TrafficMonitorWatcher - error on configHandler.processConfig
org.json.JSONException: JSONObject["edgeLocations"] not found.
```

I understand this is not one concrete issue to track. I'm just reporting my problem(s) and please help clarifying what is it that i'm missing / doing wrong and what remains as actual Traffic Control issues -- including documentation indeed :-)

**Comment by kianooshm** [comment]
Let me add that Tomcat does not start ("telnet 127.0.0.1 80" fails), but I can't find much info in TomCat logs: they end with
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
Which probably means that's the last log message we are gonna get!

Also spent some times resolving this (including copying `slf4j-log4j12-1.6.4.jar` to `/opt/tomcat/lib/`, trying other jars `slf4j-api-1.6.4.jar`, `slf4j-simple-1.6.4.jar`, but a different problem every time; could be that tomcat and traffic_monitor can't be loading slf4j both), but no luck there and that's a different story.

**Comment by smalenfant** [comment]
Are you trying to setup Traffic Router without Traffic Monitor/Traffic Ops?

**Comment by kianooshm** [comment]
No, they are both up. I don't see means to introduce traffic ops to traffic router, but i introduced traffic monitor to traffic router via the `traffic_monitor.bootstrap.hosts` property in `/opt/traffic_router/conf/traffic_monitor.properties`

**Comment by smalenfant** [comment]
Please check documentation here :
http://traffic-control-cdn.net/docs/latest/admin/traffic_monitor.html

Step 4 -
 Take the config from Traffic Ops - run : sudo /opt/traffic_monitor/bin/
traffic_monitor_config.pl

**Comment by kianooshm** [comment]
i did this. you are talking about traffic monitor. my problem is with traffic router.

In fact I pointed this out in my report above: ` It would be much nicer if, just like Traffic Monitor that has a script to pull the data it needs, Traffic Router does that too.`

But now that it does not, how can I work around the issues I listed above?

**Comment by smalenfant** [comment]
Traffic Router pulls it's configuration directly from Traffic Monitors
except for the MaxMind database and the CZF file. But the locations are
provided by the Traffic Ops Cr-Config.

The single thing I change on Traffic Router is
"traffic_monitor.bootstrap.hosts", all the rest gets updated
auto-magically. See my Ansible script below, this is all I have to do (once
jdk and tomcat is installed).

---
# file: roles/traffic-router/tasks/main.yml

- yum: name=traffic_router state=present
  notify:
   - restart tomcat

# list of ips or hostnames delimited by semicolon (;)
# traffic_monitor.bootstrap.hosts=some-traffic_monitor.company.net:80;
- lineinfile: dest=/opt/traffic_router/conf/traffic_monitor.properties
state=present regexp='^traffic_monitor.bootstrap.hosts'
              line='traffic_monitor.bootstrap.hosts={{ trafficmonitors |
join(";") }}'
  notify:
   - restart tomcat

Which version of tomcat and jdk are you using?

Example CR-Config provided to both Traffic Monitor and Traffic Router (From
Traffic Ops) :

  "config": {
    "geolocation.polling.url":
"http://hostname.tld/files/GeoLite2-City.mmdb.gz",
    "api.cache-control.max-age": "10",
    "geolocation.polling.interval": "86400000",
    "domain_name": "wcdn.cox.net",
    "ttls": {
      "AAAA": "30",
      "SOA": "86400",
      "A": "30",
      "NS": "3600"
    },
    "soa": {
      "expire": "604800",
      "minimum": "86400",
      "admin": "twelve_monkeys",
      "retry": "7200",
      "refresh": "28800"
    },
    "coveragezone.polling.url": "http://hostname.tld/files/2015-07-08.json",
    "coveragezone.polling.interval": "86400000"
  }

**Comment by kianooshm** [comment]
Thanks. I'll try your procedure shortly and let you know the result.

Right now i'm stuck with the following exception `org.json.JSONException: JSONObject["edgeLocations"] not found.` which i'd assume is related to `cache.czmap.database` in `/opt/traffic_router/conf/cache.properties`. I don't know what that property (`edgeLocations`) is and how to set it; the documentation on creating a coverage zone file (assuming it's the same as the "coverage map database") doesn't address that. Would you know?

**Comment by smalenfant** [comment]
I believe this would be because the cdn_name isn't assigned to your
cache-groups.

Please check this :
http://traffic-control-cdn.net/docs/latest/faq/administration.html#why-is-my-crconfig-json-rejected

All you need to get started is the default coverage zone map. It can be
found here:
https://github.com/Comcast/traffic_control/blob/master/traffic_ops/app/public/coverage-zone.json

Documented here :
http://traffic-control-cdn.net/docs/latest/admin/traffic_ops_using.html#rl-asn-czf

Make sure it is available via the proper parameter in Traffic Ops (search
for coverage).

Steve

**Comment by kianooshm** [comment]
Thanks. I did all those steps. That got the CRConfig going, for now.

I'm now stuck at this exception. Would you know any workaround? (BTW I did a packet capture on the Traffic Router host and it never gets to the point of contacting Traffic Monitor at all; i'm instead copying its config files manually to `/opt/traffic_router/db`)
```
INFO  2015-08-19T13:57:11.376 [main] com.comcast.cdn.traffic_control.traffic_router.core.router.StatTracker - Initializing statistics for DeliveryService [id=MyDeliveryService]
WARN  2015-08-19T13:57:11.557 [main] com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater - java.lang.ArrayIndexOutOfBoundsException: 1
java.lang.ArrayIndexOutOfBoundsException: 1
        at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.populateZoneMap(ZoneManager.java:311)
        at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.generateZones(ZoneManager.java:132)
        at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.<init>(ZoneManager.java:78)
        at com.comcast.cdn.traffic_control.traffic_router.core.router.TrafficRouter.<init>(TrafficRouter.java:82)
        at com.comcast.cdn.traffic_control.traffic_router.core.router.TrafficRouterManager.setCacheRegister(TrafficRouterManager.java:85)
        at com.comcast.cdn.traffic_control.traffic_router.core.config.ConfigHandler.processConfig(ConfigHandler.java:106)
        at com.comcast.cdn.traffic_control.traffic_router.core.monitor.TrafficMonitorWatcher$2.update(TrafficMonitorWatcher.java:106)
        at com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater.putCurrent(PeriodicResourceUpdater.java:165)
        at com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater.init(PeriodicResourceUpdater.java:145)
        at com.comcast.cdn.traffic_control.traffic_router.core.monitor.TrafficMonitorWatcher.init(TrafficMonitorWatcher.java:135)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1544)
```

Which is pointing to here:
https://github.com/Comcast/traffic_control/blob/master/traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/ZoneManager.java#L311

Can't figure out where the FQDN of a delivery service comes from; it's not in CRConfig. I assume Traffic Router creates that FQDN itself (according to this: https://github.com/Comcast/traffic_control/issues/53)

This is my coverage file:
```
{
        "coverageZones":
        {
                "MyCacheGroupEdge":
                {
                        "network6":
                        [
                                "1234:5678::/64",
                                "1234:5679::/64"
                        ],
                        "network":
                        [
                                "192.168.8.0/24",
                                "192.168.9.0/24"
                        ]
                }
        }
}
```

And this is the CRConfig:
```
{
    "contentRouters": {
        "AF-SHD-CDN03.host": {
            "profile": "CCR_CDN",
            "api.port": "3333",
            "location": "MyCacheGroupEdge",
            "ip": "xxxx (better not to expose the public IP here)",
            "status": "ONLINE",
            "ip6": "::2",
            "port": "80",
            "fqdn": "AF-SHD-CDN03.host.AF-SHD-CDN03.domain"
        }
    },
    "monitors": {
        "AF-SHD-CDN02.host": {
            "profile": "RASCAL_CDN",
            "fqdn": "AF-SHD-CDN02.host.AF-SHD-CDN02.domain",
            "location": "MyCacheGroupEdge",
            "ip": "xxxx (better not to expose the public IP here)",
            "status": "ONLINE",
            "ip6": "::1",
            "port": "80"
        }
    },
    "edgeLocations": {
        "MyCacheGroupMid": {
            "longitude": 0,
            "latitude": 0
        },
        "MyCacheGroupOrg": {
            "longitude": 0,
            "latitude": 0
        },
        "MyCacheGroupEdge": {
            "longitude": 0,
            "latitude": 0
        }
    },
    "stats": {
        "tm_user": "admin",
        "tm_host": "xxxx (better not to expose the public IP here)",
        "tm_version": "1.1.3",
        "date": 1439976355,
        "tm_path": "/tools/write_crconfig/MyCDN",
        "CDN_name": "MyCDN"
    },
    "config": {
        "domain_name": "AF-SHD-CDN03.domain",
        "ttls": {
            "A": "3600",
            "NS": "3600",
            "SOA": "86400",
            "AAAA": "3600"
        },
        "api.cache-control.max-age": "10",
        "coveragezone.polling.interval": "86400000",
        "coveragezone.polling.url": "https://xxxx/routing/coverage-zone.json",
        "geolocation.polling.url": "https://xxxx/routing/GeoLite2-City.mmdb.gz",
        "soa": {
            "retry": "7200",
            "admin": "twelve_monkeys",
            "minimum": "86400",
            "refresh": "28800",
            "expire": "604800"
        },
        "geolocation.polling.interval": "86400000"
    },
    "deliveryServices": {
        "MyDeliveryService": {
            "missLocation": {
                "lat": "0",
                "long": "0"
            },
            "coverageZoneOnly": "false",
            "matchsets": [
                {
                    "protocol": "HTTP",
                    "matchlist": [
                        {
                            "regex": "^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\\?([^#]*))?(#(.*))?",
                            "match-type": "HOST"
                        }
                    ]
                }
            ],
            "ttls": {
                "A": "60",
                "SOA": "86400",
                "NS": "3600",
                "AAAA": "60"
            },
            "bypassDestination": {
                "HTTP": {
                    "fqdn": "xxxx",
                    "port": "80"
                }
            },
            "ttl": "60",
            "ip6RoutingEnabled": "false",
            "soa": {
                "admin": "twelve_monkeys",
                "retry": "7200",
                "minimum": "30",
                "refresh": "28800",
                "expire": "604800"
            }
        }
    },
    "contentServers": {
        "AF-SHD-CDN06.host": {
            "profile": "EDGE1_CDN_520",
            "locationId": "MyCacheGroupEdge",
            "ip": "xxxx",
            "status": "REPORTED",
            "cacheGroup": "MyCacheGroupEdge",
            "ip6": "::3",
            "port": "80",
            "deliveryServices": {
                "MyDeliveryService": [
                    "^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\\?([^#]*))?(#(.*))?"
                ]
            },
            "fqdn": "AF-SHD-CDN06.host.AF-SHD-CDN06.domain",
            "interfaceName": "eth0",
            "hashCount": 999,
            "type": "EDGE",
            "hashId": "AF-SHD-CDN06"
        }
    }
}
```

**Comment by smalenfant** [comment]
Your delivery service regexp seems possibly a bit wrong. Could you create a
test DNS delivery service with a simple regex like "test" for example?

http://traffic-control-cdn.net/docs/latest/admin/traffic_ops_using.html?highlight=delivery%20service#rl-ds-regexp

Also, I would change your domain_name to something valid.

**Comment by elsloo** [comment]
You need to use a different regex.  The one in your example will not work.  Try using something like this and see what happens: .*\.test\..*

Additionally, you should never stage the CRConfig manually; in fact, that's the exact opposite of what you should be doing.  If Traffic Router is not communicating with Traffic Monitor, you need to fix that issue first, then everything else should start falling into place.  Without Traffic Monitor the CRConfig is mostly useless.

Lastly, in the future please post questions such as this on our Google group linked from traffic-control-cdn.net.  We use Github to track bugs and features in the software, not as an avenue to troubleshoot configuration issues.  If through the course of the discussion we discover an issue in the software we will open an issue on Github.  I will leave this issue open for the time being, but will close it when you get things working.

**Comment by kianooshm** [comment]
Thanks smalenfant and elsloo. Changing the regex got Traffic Router one step further.

I'm closing the issue now. Will post in Google groups next time. This issue originally started off with a request for documentation, but turned into a configuration mystery.
