### ISSUE TITLE
The hardware tab in Traffic Ops needs some lookin' at. 

### ISSUE THREAD

**Issue by petrocc** [Comcast/traffic_control#458]
The hardware tab in Traffic Ops returns so much data that firefox thinks the javascript that generates the tables has timed out.

Sometimes twice before the table is rendered. 

There's so much data that I suspect it's current form is un-usable.

**Comment by dangogh** [comment]
Is this a duplicate of #325?

**Comment by petrocc** [comment]
Probably close enough to a duplicate that they can be merged.

**Comment by dewrich** [comment]
Solved by Issue: #325
