### ISSUE TITLE
Only servers of type "MID" and "EDGE" should be considered eligible parents.

### ISSUE THREAD

**Issue by knutsel** [Comcast/traffic_control#464]

**Comment by limited** [comment]
When would someone want to use an EDGE cache as the parent of another EDGE? Sideloading a cache?

**Comment by knutsel** [comment]
When there is a deeper layer of maybe non standard hosts that get configured by Extensions. This would normally not happen and the parent-child relation enforced by the cache-group hierarchy would always be a mid-edge thing. 

Having all cache types (MID, EDGE) and ORGs as eligible parents seems the most flexible?

**Comment by smalenfant** [comment]
Edges can listen on port 8080. Could this be used to do EDGE->EDGE->MID hierarchy? Probably only need a Traffic Ops change to change the parent config on that deeper EDGE.
