### ISSUE TITLE
API versioning

### ISSUE THREAD

**Issue by hbeatty** [Comcast/traffic_control#498]
I'm curious why the API version is different from the TO or TC version. Is it for backward compatibility?

I'm wondering if it makes sense for the app that is calling the API to request the version that it is expecting and then if the API no longer supports that version it would return an error.

**Comment by dewrich** [comment]
Good question, 

The API version that is depicted in the Traffic Ops url: ie: /api/1.2, needs to be stable.  This minimizes client integration churn as well as gives the API client an assumption that major changes haven't taken place (meaning minimal code changes on their side)

That being said, we are still working out the version issues across all of Traffic Control, but edge cases like this make that decision more challenging.

In the future, I'm not sure if you are aware but we have a forum that you can post to that is a better avenue for these types of topics.  Issues are for problems to be reported in Traffic Ops.

traffic_control@googlegroups.com 

-Dewayne
