### ISSUE TITLE
ORT should not process a config file that is missing the header comment

### ISSUE THREAD

**Issue by mtorluemke** [Comcast/traffic_control#502]
The current header comment includes "DO NOT EDIT - $hostname_short", so should be a fine thing to check for.

**Comment by knutsel** [comment]
maybe we should put an md5sum or something in the header that ort install can check?

**Comment by mtorluemke** [comment]
i like!

**Comment by mtorluemke** [comment]
Maybe add it as an HTTP header, to avoid the cyclic nature of computing the md5.
