### ISSUE TITLE
TO: rpm build exit status not consistent

### ISSUE THREAD

**Issue by dangogh** [Comcast/traffic_control#507]
build_rpm.sh needs to check for error status on each command.  Some are currently checked, but many are not,  and missing a bad command can show "good" status in Jenkins on a failed build.

**Comment by mtorluemke** [comment]
@dangogh: is this still being worked?

**Comment by dangogh** [comment]
not active on it right now,  but adding to it with other work..   It'll take some time to get all cmds covered..

**Comment by smalenfant** [comment]
We are now building with docker.
