### ISSUE TITLE
TO: Combine cache key change and dropping of query strings

### ISSUE THREAD

**Issue by mtorluemke** [Comcast/traffic_control#511]
Not sure exactly how best to do this. Perhaps:
1. Get rid of the drop_qstring column, and beef up the 'recipes' for the cacheurl field.
2. Add 'cache_key_string' column, and add smarts to combine the two when both fields are set.

**Comment by MattMills** [comment]
Moved to Jira https://issues.apache.org/jira/browse/TC-300
