### ISSUE TITLE
Missing regex_revalidate config from Traffic Ops

### ISSUE THREAD

**Issue by kianooshm** [Comcast/traffic_control#513]
I keep getting the following error in traffic servers when running `traffic_ops_ort.pl`:

`ERROR Result from curling https://x.x.x.x/Trafficserver-Snapshots/MyCDN/regex_revalidate.config is HTTP 404!`

I've manually created `Trafficserver-Snapshots` and `Trafficserver-Snapshots/MyCDN` under `/opt/traffic_ops/app/public` as per the discussion [here](https://groups.google.com/d/msg/traffic_control/lo87Dc1xGyQ/BoX3Tna8CQAJ), but Traffic Ops does not creating anything under the dirs I made. Creating this issue as requested.

**Comment by knutsel** [comment]
I'm pretty sure this is not something to be worried about. That file will only get created when there is a purge active. Having said that TO should gen an empty file to prevent this error.

**Comment by knutsel** [comment]
didn't read the whole thing; the not creating snapshots is worrisome.

**Comment by smalenfant** [comment]
Make sure permissions are set correctly on /opt/trafficops. Seems like you
made have created directory as root. They should chown to trafops ???

**Comment by kianooshm** [comment]
I run the traffic ops service as root so permissions shouldn't be a problem ... Everything else in there is also root.
