### ISSUE TITLE
Invalid DS regex causes nasty exception and unexpected results

### ISSUE THREAD

**Issue by elsloo** [Comcast/traffic_control#514]
If a host regex (probably others) is specified as a plain string, rather than a real regex (e.g.: test vs ._.mydeliveryservice.._), the following exception occurs in Traffic Router, and the user would have to be watching the logs to see that something went wrong.  Additionally, it is not clear why the failure occurred.

Improve TO in general such that the regex is clearly defined (documented?) and potentially checked so that it doesn't get added to the CRConfig until it is what we expect to see.  Additionally, discuss whether we want to support specific strings (e.g.: test) instead of a full regex. Doing so seems to be counter to the intent of the regex in the first place, so I do not think that this is a viable option at this time.

`WARN  2015-09-01T14:25:07.237 [New I/O worker #1] com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater - 1
java.lang.ArrayIndexOutOfBoundsException: 1
        at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.populateZoneMap(ZoneManager.java:311)
        at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.generateZones(ZoneManager.java:132)`

**Comment by smalenfant** [comment]
Jeff, the problem is that the first regex needs to be the special one
(which I don't remember everytime). then the second one (if you want to
CNAME) is a normal text one like "old.cdn.domain.tld". It's almost like we
need to use the "xml id" as default for the service name and wrap around
the prefix and domain_name.
