### ISSUE TITLE
ipv6 address required on edge cache for ip_allow.config to get written out on mid

### ISSUE THREAD

**Issue by sandmanahoy** [Comcast/traffic_control#523]
The ip_allow.config for the mid cache is not updated by the ORT script (Fatal Error: Can&#39;t call method &quot;network&quot; on an undefined value at blib/lib/NetAddr/IP.pm (autosplit into blib/lib/auto/NetAddr/IP/coalesce.al) line 1273). The only way to get it to update is to add an ipv6 address for any edge caches (or possibly only one edge cache) that are children of the mid cache being updated.

**Comment by limited** [comment]
CDETS CSCuw28583

**Comment by knutsel** [comment]
closed - this has all been rewritten
