### ISSUE TITLE
Expose edge fqdn and edge alias fqdn(s) for a delivery service through the traffic ops api

### ISSUE THREAD

**Issue by mitchell852** [Comcast/traffic_control#53]
Currently the /api/1.1/deliveryservices/:id.json endpoint returns values such as:

- delivery service protocol
- delivery service content routing type
- matchlist with pattern and type

Using these values and the correct logic, you can construct the delivery service edge fqdn and one or more edge alias fqdns.

Rather than the traffic ops api consumer having to construct these fqdns expose them through the api to ensure the correct logic is applied. The logic is found in get_example_urls() in this file https://github.com/Comcast/traffic_control/blob/master/traffic_ops/app/lib/UI/DeliveryService.pm

**Comment by mitchell852** [comment]
something like would be excellent!:

edgeFQDN: 'edge.foo.bar.com',
edgeAlialFQDNs: [ 'alias1.com', 'alias2.com' ] or empty array if none

**Comment by elsloo** [comment]
Perhaps instead of calling this "edge" something, we call it "routing name," "entry point(s)," or something to that effect.  The data you wish to display is the entry point(s) into the CDN, which is technically the edge, however, for HTTP delivery services the entry point is the Traffic Router.  These names differ between delivery service types (HTTP vs DNS).

**Comment by knutsel** [comment]
is the thing we used there (tr and edge, I think it is now) in the DB? Or just in a properties file?

**Comment by mitchell852** [comment]
@elsloo - yes, i want the "edge fqdn" which can look like edge.foo.bar.com or ccr.foo.bar.com (depending on dns or http) or whatever the entry point into the cdn is...

**Comment by elsloo** [comment]
If/when we implement #62, we can expose the data for this issue.

**Comment by mitchell852** [comment]
As I feared, the lack of this property on a delivery service has resulted in a bug in the Traffic Portal (a consumer of the API). I would be happy simply with a property like this:

exampleUrls: [ 'url1', 'url1', ...] where the array is populated using the logic found in get_example_urls () in https://github.com/Comcast/traffic_control/blob/master/traffic_ops/app/lib/UI/DeliveryService.pm

the new property would be in the following api endpoints:

/api/1.1/deliveryservices.json
/api/1.1/deliveryservices/:id.json
