### ISSUE TITLE
Delivery service UI allows multiple regexes with the same order

### ISSUE THREAD

**Issue by elsloo** [Comcast/traffic_control#531]
The edit delivery service UI allows multiple regexes with the same value in the order field.  This causes unintended consequences downstream in Traffic Monitor, for example, when two HOST regexes are specified with order = 0.  Modify Traffic Ops such that this UI allows only one regex per order value.

**Comment by elsloo** [comment]
The following query can be used to identify any delivery services configured with more than one regex with a given set number value:

```select d.xml_id, r.set_number, count(*) from deliveryservice d, deliveryservice_regex r where d.id = r.deliveryservice group by d.xml_id, r.set_number having count(*) > 1;```

**Comment by robert-butts** [comment]
Seems like it'd be ideal if the GUI didn't allow duplicate orders either, i.e. selected order numbers were removed via JS from other dropdowns. Or better yet, order was determined by dragging and dropping. But, not worth doing in 1.x.
