### ISSUE TITLE
Influx summary query returns results not found in the corresponding series query (i.e. max and min)

### ISSUE THREAD

**Issue by mitchell852** [Comcast/traffic_control#539]
For example, the influx series query results may look like this:

[
  [time, value],
  [time, 10],
  [time, 20],
  [time, 34],
  [time, 26]
]

and the influx summary query results for the same timeframe may look like:

{
  time: x,
  mean: y,
  min: 8,
  max: 75
}

notice how the min=8 and max=75 is strange because 8 and 75 are not found in the series query. this is because the series query is being grouped into 60s intervals (which is an average of 6 10s intervals) but the summary query looks at every value recorded in influx (on the 10s interval) between the timeframe.

so in this example, i would expect min=10 and max=34

maybe it's possible to run the summary query against the series query results?? like a subselect query like this:

SELECT mean(value), percentile(value, 5), percentile(value, 95), percentile(value, 98), min(value), max(value), count(value) FROM (SELECT sum(value)/count(value) FROM tps_total WHERE cachegroup = 'total' AND deliveryservice = 'ds-name' AND time >='2015-09-17T03:38:00-06:00' AND time <= '2015-09-17T15:38:00-06:00' GROUP BY time(60s), cachegroup)

this bug pertains to the following api endpoint /api/version/deliveryservice_stats.json when data source is influx.

here are a couple sample influx queries:

summary_query #-> $VAR1 = 'SELECT mean(value), percentile(value, 5), percentile(value, 95), percentile(value, 98), min(value), max(value), count(value) FROM tps_total WHERE time >= \'2015-09-17T03:38:00-06:00\' AND time <= \'2015-09-17T15:38:00-06:00\' AND cachegroup = \'total\' AND deliveryservice = \'ds-name\'';

series_query #-> $VAR1 = 'SELECT sum(value)/count(value) FROM tps_total WHERE cachegroup = \'total\' AND deliveryservice = \'ds-name\' AND time >=\'2015-09-17T03:38:00-06:00\' AND time <= \'2015-09-17T15:38:00-06:00\' GROUP BY time(60s), cachegroup';

**Comment by mitchell852** [comment]
1.1.7 will be using an influxdb continuous query that rolls up raw data from 10sec intervals to 60sec intervals, so both the influx series query and the influx summary query are now looking at the same level of data (both looking at values every 60secs) making this a non-issue.

**Comment by mitchell852** [comment]
this is not fixed. :( if you pass in another interval like 1h, this issue again occurs. 

this will require a summary query based on a series query or basically a nested query as the issue suggested and nested queries are not yet supported in influxdb - https://github.com/influxdb/influxdb/issues/52

**Comment by dangogh** [comment]
moved to https://issues.apache.org/jira/browse/TC-303
