### ISSUE TITLE
download_web_deps, CURLOPT_TIMEOUT too low

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#54]
It seems like there is bug in curl libraries which prevents it from fetching the URL within the timeout specified in download_web_deps when a system doesn't have IPv6 connectivity and IPv6 is enabled (even IPv6 locallink), it takes more than 5 seconds to resolve. 

Workaround : 
$curl->setopt(CURLOPT_TIMEOUT, 15);

But then this makes it really slow to download the files needed. Other workaround is to disable IPv6 at the host.

**Comment by knutsel** [comment]
can we run curl --4 ?

**Comment by smalenfant** [comment]
--4 works just fine. I should have specified.

**Comment by mtorluemke** [comment]
Closed with a2fbfd7527eebad9716c6cce76ce0c80ffba44e3
