### ISSUE TITLE
500 Internal Server Error on /api/1.2/deliveryservice_stats.json when logged in as admin

### ISSUE THREAD

**Issue by mitchell852** [Comcast/traffic_control#543]
To reproduce:

- login as an user with role=admin
- access the following api endpoint:

/api/1.2/deliveryservice_stats.json?deliveryServiceName=delivery-service-name&endDate=2015-09-21T09:01:00-06:00&exclude=&interval=60s&metricType=kbps&serverType=edge&startDate=2015-09-18T09:01:00-06:00

**Comment by mitchell852** [comment]
Error is:

[2015-09-21 09:02:35,920] [ERROR] Can't locate object method "is_admin" via package "Extensions::TrafficStats::API::DeliveryServiceStats" at local/lib/perl5/Mojolicious.pm line 126.

**Comment by mitchell852** [comment]
might not be a bad idea to check it against all roles...

**Comment by dangogh** [comment]
Fixed bug in implementation-specific extension

**Comment by mitchell852** [comment]
looks good. thx.
