### ISSUE TITLE
Add a way to select query string parameters to drop at edge

### ISSUE THREAD

**Issue by knutsel** [Comcast/traffic_control#56]
for example input url ::

```
  http://host/path?key1=something&key2=somethingelse&key3=foo
```

Want to set per delivery service which of the keys get dropped or used in cachekey and passed up (regex_remap case).

**Comment by knutsel** [comment]
so config should be like::

     keep:key2

or ::

     drop: key1,key3

**Comment by dg4prez** [comment]
https://issues.apache.org/jira/browse/TC-290
