### ISSUE TITLE
traffic_ops_scripted.js doesn't work with newer versions of grafana

### ISSUE THREAD

**Issue by dneuman64** [Comcast/traffic_control#569]
traffic_ops_scripted.js which is used to create custom graphs works with grafana 2.0.2 but does not work with newer versions of grafana (specifically 2.13).  It should be updated to work with newer versions.

**Comment by smalenfant** [comment]
Apparently you can't use "type" as a variable name anymore. Renaming it to typeGraph works (but you also need to rename the query string). Why not separating them in 3 scripts and drop that type? Would probably make it easier to change/debug in the future as well. If agreed, I'll send a pull request.
