### ISSUE TITLE
Web UI Unexpected RuntimeException

### ISSUE THREAD

**Issue by skoval200** [Comcast/traffic_control#594]
RPM version: traffic_monitor-1.1.1-443149274.el6.x86_64
Checking status via Web UI generates Unexpected RuntimeException

Last cause: No enum constant com.comcast.cdn.traffic_control.traffic_monitor.health.HealthDeterminer.AdminStatus.PRE_PROD
WicketMessage: Exception in rendering component: [ListItem [Component id = 42]]

**Comment by mtorluemke** [comment]
Fixed on TO side: https://github.com/Comcast/traffic_control/commit/702f628058fa18643e057d9677a344d46b6fba08
