### ISSUE TITLE
Setting server in PRE_PROD causes Traffic Monitor exceptions

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#598]
I believe all Traffic Monitors will be in that state about the same time. Traffic Router are getting ConnectionExceptions but still works (but can't get Health updates???).

```Last cause: No enum constant com.comcast.cdn.traffic_control.traffic_monitor.health.HealthDeterminer.AdminStatus.PRE_PROD
WicketMessage: Exception in rendering component: [ListItem [Component id = 0]]```

**Comment by mtorluemke** [comment]
Fixed on TO side in commit: https://github.com/Comcast/traffic_control/commit/702f628058fa18643e057d9677a344d46b6fba08
