### ISSUE TITLE
TrafficStats exits when Traffic Ops is unavailable

### ISSUE THREAD

**Issue by lwickline** [Comcast/traffic_control#615]
The trafficstats processes will exit when traffic ops is unreachable or not available. This should be changed to continue to retry and continue gracefully .

**Comment by smalenfant** [comment]
What about caching the configuration so it can continue when unreachable?

**Comment by PSUdaemon** [comment]
This is not a thing anymore.

**Comment by dneuman64** [comment]
which means, this is fixed in 1.1.7

**Comment by PSUdaemon** [comment]
Moreover, the entire code path that caused this issue no longer exists. When the code was refactored and merged together the offending code was expunged.
