### ISSUE TITLE
Failed to install Traffic Ops 1.2.0/1.1.6/1.1.5

### ISSUE THREAD

**Issue by Vuuo** [Comcast/traffic_control#656]
Hi,

I'm new to traffic control. It looks awesome. We are trying to setup our first traffic ops node. Spent hours and hours, but none of them works.

The OS is CentOS 6.5. We tried 1.2.0, 1.1.6, and 1.1.5. All of them failed during db creation, seeding, migration. Grabbed the package from http://traffic-control-cdn.net/downloads/index.html

With 1.2.0, it cannot seed the profiles, saying cannot not find colume 'cdn_id'
With 1.1.6, it cannot create the database. saying 'failed to create the database'
With 1.1.5, the insert failed. 
```
Cannot add or update a child row: a foreign key constraint fails (`traffic_ops_db`.`profile_parameter`, CONSTRAINT `fk_atsprofile_atsparameters_atsparameters1` FOREIGN KEY (`parameter`) REFERENCES `parameter` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION)`
```

**Comment by mtorluemke** [comment]
Thanks for the issue -- you can discuss this in (near) real time on our Slack channel: "traffic-control-cdn". Or, for a slower response, you can post an issue on the Google Groups: groups.google.com/forum/#!forum/traffic_control

**Comment by Vuuo** [comment]
May I get the invitation to join the Slack channel please? s.hou at vuuo dot com
Thank you very much!

**Comment by dneuman64** [comment]
It is on the way!

**Comment by elsloo** [comment]
```Database initialization succeeded.
Seeding cdn data...
     Inserting cdn: {Name:cdn} 
Seeding profile data...
Couldn't prepare profile insert statment
Error 1054: Unknown column 'cdn_id' in 'field list'```
