### ISSUE TITLE
CDN "ALL" is default, But only applicable to certain components

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#668]
On my first attempt to configure Traffic Ops 1.2.0, I created my servers but they all got assigned to a CDN named "ALL". Apparently this configuration is only used for Traffic Stats and Vaults.

By default, there probably should not be any values in following fileds..  
 - CDN
 - Cache Group
 - Physical Location
 - Type
 - Profile

I've seen a lot of errors from different people assigning wrong values for any of those which created some problems. It might be difficult to set those up in order so it might not be possible to insert at least "ALL" in CDN for Edge/Mid/CCR/RASCAL.

**Comment by jheitz200** [comment]
The "ALL" CDN is no longer included in fresh installs.  I am going to close this issue but please re-open if you continue to find problems.

Thanks
Jackie
