### ISSUE TITLE
Traffic Ops 1.2.1 - Cannot configured Delivery Service correctly

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#670]
Having some problem configuring Delivery Services in 1.2.1. Please see screenshot using Chrome and/or Safari.

<img width="512" alt="ds_screen_issue" src="https://cloud.githubusercontent.com/assets/3803592/10590601/9ce6cf48-767f-11e5-9fbc-c762cbc95085.png">

**Comment by jheitz200** [comment]
@smalenfant are you still seeing an issue with this?

**Comment by smalenfant** [comment]
@jheitz200 No, this can be closed. Although there is still a bug in there if you select ANY_MAP and go back type DNS for example, the fields don't get reset properly on the page.

**Comment by jheitz200** [comment]
ok, there is another issue for ANY_MAP https://github.com/Comcast/traffic_control/issues/740

I am going to close this issue, please re-open it if you see problems again.
Thanks
Jackie
