### ISSUE TITLE
syncds and Query String Handling bug

### ISSUE THREAD

**Issue by skoval200** [Comcast/traffic_control#727]
syncds does not add **@pparam=cacheurl_qstring.config** to the remap.config file after changing/setting   **Changing  Query String Handling** to "1 - ignore in cache key, and pass up" in Traffic Ops

**Comment by jheitz200** [comment]
According to @skoval200 this issue has been resolved, please re-open if the issue occurs again.
Thanks
Jackie

**Comment by smalenfant** [comment]
@skoval200 I have the same problem with ORT 0.53c. Could you point out the fix please?

**Comment by mtorluemke** [comment]
@smalenfant: does the remap.config entry look correct?

**Comment by smalenfant** [comment]
@mtorluemke yes, but the config file is missing.

**Comment by mtorluemke** [comment]
the config file = cacheurl_qstring.config ?

**Comment by smalenfant** [comment]
Sorry. Yes.

**Comment by mtorluemke** [comment]
did you check that pesky 'location' parameter for that config file, and your profile?

**Comment by smalenfant** [comment]
I'll check when I can. Also, seems like the cacheurl parameter was included only at the Mid and not the Edge. But maybe I didn't see it since I was in firefighter mode...

**Comment by smalenfant** [comment]
@mtorluemke Thanks, that was it. 

Added name: location, config: cacheurl_qstring.config, value: /opt/trafficserver/etc/trafficserver

Some values have `/opt/trafficserver/etc/trafficserver/` and some `/opt/trafficserver/etc/trafficserver`. Doesn't seem to make a difference.

Can `cacheurl.config` be removed?
