### ISSUE TITLE
Create UI for default DNS for GenIso. 

### ISSUE THREAD

**Issue by petrocc** [Comcast/traffic_control#78]
This is an update to issue #55. In the current patch it reads the DNS servers from /etc/resolv.conf on the Traffic Ops server. Ideally there would be a way to set two default DNS servers through the Web UI and a way to override them on either the (or both) physical location field or the cache group field. 

While we're at it, there are some other defaults in GenIso.pm that probably should be editable via the interface: 

 23 my $filebasedir = "/var/www/files";
 24 my $ksfiles_parm_name = "kickstart.files.location";
 25 my $ksfiles_configfile_name = "mkisofs";
 26
 27 # This is the directory we put the configuration files in for kickstart &
 28 # scripts to process:-
 29 my $install_cfg = "ks_scripts";

**Comment by dneuman64** [comment]
moved to apache jira.  Closing.
https://issues.apache.org/jira/browse/TC-286
