### ISSUE TITLE
Traffic Ops - Add customer email mapping to delivery service for triggered change notifications 

### ISSUE THREAD

**Issue by ghost** [Comcast/traffic_control#782]
Traffic Ops - Add customer email mapping to delivery service for triggered change notifications

Example: When a MID Tier Cache is added, removed and/or re-ip'd a triggered email would be sent to all customers advising them of the change.

This same type of email notification can be extrapolated to a number of triggered events where a specific customer or all customers are notified of the change or situation. ( situation ~= outage, Origin failures ... etc )

**Comment by knutsel** [comment]
three extended description fields were added for this.
