### ISSUE TITLE
Unable to map same CNAME to multiple delivery services.

### ISSUE THREAD

**Issue by elsloo** [Comcast/traffic_control#788]
Existing logic in `UI::Federation::create()` prevents a target CNAME from being used with more than one delivery service.  Specifically, this:

```
    my $existing_fed = $self->db->resultset('Federation')->search( { cname => $cname } )->get_column('cname')->single();
    if ($existing_fed) {
        $self->field('federation.cname')->is_equal( "", "A Federation with name \"$cname\" already exists." );
    }   
```

**Comment by dewrich** [comment]
Spoke with Jan about this and the likelihood of multiple delivery services using the same cname is unlikely and that this is still a valid check
