### ISSUE TITLE
NET::CIDR not validating IPV6 addresses correctly.

### ISSUE THREAD

**Issue by dneuman64** [Comcast/traffic_control#818]
According to NET::CIDR this is not a valid IPV6 address:  2607:f8b0:4001:c01:0:0:0:102, but this is:  2607:f8b0:4001:c01::102.  The two addresses are the same and both are valid, just the second one is in "preferred" format per this draft RFC:  http://tools.ietf.org/html/draft-ietf-6man-text-addr-representation-04

**Comment by dewrich** [comment]
@jheitz200 Try evaluating this library: http://search.cpan.org/~cdolan/Net-IP-Match-Regexp-1.01/lib/Net/IP/Match/Regexp.pm
