### ISSUE TITLE
Add cron entry that will clear out iso directory to install RPM

### ISSUE THREAD

**Issue by jpappa200** [Comcast/traffic_control#821]
I have created a file in /etc/cron.d/ called clean_isos which contains the following line.

00 04 * * * root /bin/find /opt/traffic_ops/app/public/iso/*.iso -mtime +7 -exec /bin/rm {} \;

This will delete any .iso files that are in the /opt/traffic_ops/app/public/iso/ directory that are older than 7 days. I would like to get this added to the RPM build so it will always be there.

**Comment by smalenfant** [comment]
Instead of having a cron entry, could we simply clean up when geniso is triggered? That might be cleaner than installing cron entries.

**Comment by dewrich** [comment]
I think the intent is to keep the isos around for a while, currently we don't have a background job facility within TrafficOps

**Comment by dewrich** [comment]
@jpappa200 We should consider packaging these scripts somewhere so that they can be referenced from the .rpm

**Comment by dneuman64** [comment]
I think the precedent is there.  If you put the file in the traffic_ops/etc/cron.d, I think the installer will do the right thing when installing traffic ops. 
see here:  https://github.com/Comcast/traffic_control/tree/master/traffic_ops/etc/cron.d

**Comment by elsloo** [comment]
This was resolved via #1254.
