### ISSUE TITLE
Updating a user to have a username that is already used results in fatal error

### ISSUE THREAD

**Issue by mitchell852** [Comcast/traffic_control#850]
To reproduce, in the TO UI, edit a user and update their username value to equal a username that is already being used.

In addition, this api call should fail gracefully as well when a duplicate username is being used:

api/{version}/user/current/update 

gracefully == return 400 bad request with something like "Username already taken" in the alerts array.

**Comment by dewrich** [comment]
Fixed by https://github.com/Comcast/traffic_control/pull/849
