### ISSUE TITLE
Clean install profiles are out of date and incomplete.

### ISSUE THREAD

**Issue by knutsel** [Comcast/traffic_control#855]
The profiles for edges are ATS 520, the mid is 421 (from the name). The mid profile has only 4 entries in it. 

Let's keep this open until I get further into the 1.3 test install until we try to fix it.

**Comment by knutsel** [comment]
Also:

ERROR: No location for rascal-config.txt found in traffic_ops, bailing!

This prevents Traffic Monitor from getting installed. I'll look into updating all profiles / parameters for 1.3.

**Comment by smalenfant** [comment]
@knutsel The `ERROR: No location for rascal-config.txt found in traffic_ops, bailing!` was resolved by using the proper RASCAL_CDN (or TM_CDN???) on my Traffic Monitor. But I agree the profiles are old and outdated. I could take a stab at fixing this during a fresh install.

**Comment by smalenfant** [comment]
@knutsel Can we simply export some current profiles (cleaned up) available in the repo for folks to download? Maybe create a documentation page for different type of HW/VM.

**Comment by mtorluemke** [comment]
In the works for 1.4 -- should be ready soon.
