### ISSUE TITLE
Traffic Ops hardware Tab fails to populate when there are too many rows returned

### ISSUE THREAD

**Issue by lwickline** [Comcast/traffic_control#859]
The API @ /api/1.2/hwinfo.json will fail with an empty reply from the server. 

The hardware page just never loads. 

example curl:

time curl -H 'Cookie: mojolicious=blah' -Lvsk "https://server.server.comt/api/1.2/hwinfo.json" -o /dev/null
*   Trying 1.2.3.4...
* Connected to server.server.com (1.2.3.4) port 443 (#0)
* TLS 1.2 connection using TLS_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: server.server.com
* Server certificate: COMODO RSA Organization Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
* Server certificate: AddTrust External CA Root
> GET /api/1.2/hwinfo.json HTTP/1.1
> Host: tm.comcast.net
> User-Agent: curl/7.43.0
> Accept: */*
> Cookie: mojolicious=blah
> 
* Empty reply from server

**Comment by dewrich** [comment]
Fixed by PR: #859
