### ISSUE TITLE
Build process shouldn't 'go get' the influxdb client

### ISSUE THREAD

**Issue by dneuman64** [Comcast/traffic_control#875]
It looks like when we are building traffic stats, we do a `go get -v`  which appears to have caused issues with influxdb. With traffic stats 1.3.0 RC3, when data is written to infuxdb (0.9.4.2) it has an incorrect timestamp.  I have seen this before and it was related to using a version of the client that was ahead of the currently installed influxdb version.    I know there isn't a good way to tell `go get` to use a certain version, but maybe we should handle this differently?  The Influxdb client appears to be backward compatible (the 0.9.3 version of the client works with 0.9.4.2) so maybe we should handle this manually and identify a minimum version supported.

**Comment by dangogh** [comment]
we'll need to discuss the best way to handle this..
