### ISSUE TITLE
Generate SSL Key submit button

### ISSUE THREAD

**Issue by G4m30v3r** [Comcast/traffic_control#876]
The "submit" button for generating new SSL keys verbiage is "Load Keys" - "Generate Key" or "submit" would be more intuitive.

**Comment by dneuman64** [comment]
I just checked and for generating keys the button text is "Generate Keys".  The text for pasting keys is "Load Keys".  However, if you first choose "Paste Existing Keys" and then "Generate New Keys" then the button stays as "Load Keys".
