### ISSUE TITLE
Delivery Services that are both http and https do not make it into ssl_multicert.config

### ISSUE THREAD

**Issue by mtorluemke** [Comcast/traffic_control#88]
Should have a line like:

dest_ip=*	 ssl_cert_name=delivery-service_cert.cer	 ssl_key_name=delivery-service.key

**Comment by knutsel** [comment]
Do you have a repro scenario? I tried to just convert a DS from http to http + https, and I see the line getting added to the multicert file just fine.

**Comment by knutsel** [comment]
I think this may be because it's very tempting to Add SSL keys before saving the protocol change - changing UI so you have to save the protocol change first, only when changed the "Add SSL Keys" button appears.

**Comment by knutsel** [comment]
Confirmed it was the UI confusion.
