### ISSUE TITLE
Cannot scroll through list of caches in cache group tree for Delivery Service Server assignments

### ISSUE THREAD

**Issue by trevorackerman** [Comcast/traffic_control#888]
I added more than 80 caches to a cache group.

In Chrome with the default font size on a large display I cannot scroll down within the modal dialog to allow me to check or uncheck caches at the end of the list.

**Workaround** If I reduce my browser's font size, I can see the whole list of caches in the cache group and can check and uncheck them

**Comment by guzzijason** [comment]
I believe this is resolved; if not, there is a new (different) UI about to be released which will make this one moot.
