### ISSUE TITLE
TO: server upload csv has no entry for ip6Netmask

### ISSUE THREAD

**Issue by dangogh** [Comcast/traffic_control#939]
comparing json output from /servers.json and field order in the uploadservercsv code,  the ip6Netmask field in the json does not have a column in the csv.  Unfortunately,  adding a column would make any existing csv files not load.

**Comment by dangogh** [comment]
The specific code location is the method UI::UploadHandlerCsv::getParamHashRef -- around line 196 in master.

**Comment by smalenfant** [comment]
There is no IPv6 netmask in the server table. Closing
