### ISSUE TITLE
TO: Fresh install, No MID profiles found for CDN: cdn

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#943]
Not sure if that's something new in 1.3, but we can't generated a CR-Config without a MID Profile. Is having a MID a MUST?

```
Traffic Ops fatal error occurred while processing your request. 
Error at line 75 (  my $json = UI::Topology::gen_crconfig_json( $self, $cdn_name );) 
No MID profiles found for CDN: cdn
```

**Comment by molgun** [comment]
Hey @smalenfant,

I have the same issue how did you resolve this?

**Comment by smalenfant** [comment]
You have to configure a MID in the server table. I don't think there is anyway around it currently.
