### ISSUE TITLE
Retrieving SSL keys by hostname doesn't work

### ISSUE THREAD

**Issue by mtorluemke** [Comcast/traffic_control#95]
...if xml_id doesn't match the first host regex

**Comment by knutsel** [comment]
Not reproducible.

**Comment by mtorluemke** [comment]
This happens when there is a duplicate pattern in the regex table -- which happens when the same regex is used across CDNs. I'll come up with something to fix.

**Comment by mtorluemke** [comment]
https://github.com/Comcast/traffic_control/commit/024ad8aa1edb923759cf881e01c3f369e94006b0
