### ISSUE TITLE
TO: Invalidate content API call 

### ISSUE THREAD

**Issue by bflanigan** [Comcast/traffic_control#998]
I issued an API call to invalidate some content for an ANY_MAP delivery service:

[coolguy@randomhost ccdn] curl  -o $HOME/foobar.com.stuff_purge.out -b /tmp/cookie -c /tmp/cookie --insecure -H 'Accept: application/json' -X POST --data '{ "dsId":"441", "regex":"/\d+/foobar.com/stuff1/", "startTime":"2016-01-29 18:06:40", "ttl":168 }' https://qa-host.kabletown.net/api/1.2/user/current/jobs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
214   116  116   116    0    98     10      8  0:00:11  0:00:11 --:--:--     5

[coolguy@randomhost ccdn] cat  $HOME/foobar.com.stuff_purge.out
{"alerts":[{"level":"success","text":"Successfully created purge job for: \/\d+\/foobar.com\/stuff1\/(TTL:168h)"}]}[Fri Jan 29][18:07:23]
[coolguy@randomhost ccdn]

I then went into the UI and issued a separate invalidation request but changed the URI slightly (stuff1 became stuff2). 

If you run a report, you can see the difference: 

[root@midhost coolguy]# /opt/ort/traffic_ops_ort.pl report error https://qa-host.kabletown.net admin:xxxxxxxx
Fri Jan 29 18:17:41 UTC 2016
Version of this script: 0.55c
ERROR Traffic Ops is signaling that an update is waiting to be applied.
ERROR Lines for /opt/trafficserver/etc/trafficserver/regex_revalidate.config from Traffic Ops do not match file on disk.
ERROR Config file regex_revalidate.config line only in TrOps:   /\d+/foobar.com/stuff1/ 1454263660
ERROR Config file regex_revalidate.config line only in TrOps:   http://slow-([a-z0-9]+)-([0-9]+).sys.kabletown.net/\d+/foobar.com/stuff2 1454264281
[root@midhost coolguy]#

We're missing the hostname regex on the API call.

**Comment by mitchell852** [comment]
this appears to be a bug with the /api/1.2/user/current/jobs route. 

if you try to create a purge job on an "any_map" deliveryservice you get a response like:

Successfully created purge job for: /path/to/content/content.jpg (TTL:168h)

If you try to create a purge job on a "non any_map" deliveryservice you get a response like:

Successfully created purge job for: http://origin.com/path/to/content/content.jpg (TTL:168h)

the 2nd behavior is correct.

**Comment by dg4prez** [comment]
https://issues.apache.org/jira/browse/TC-306
